### ISSUE TITLE
Move `reth_network::FullNetwork` to `reth-network-api`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10002]
### Describe the feature

Move `reth_network::FullNetwork` trait into `reth-network-api`

### Additional context

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/10003
- [ ] https://github.com/paradigmxyz/reth/pull/10006 
- [ ] https://github.com/paradigmxyz/reth/pull/10062
```
