### ISSUE TITLE
Tracking: Pectra devnet-3

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#10079]
### Describe the feature

These are the required changes for pectra devnet-3 from pectra devnet-1 and 2.

```[tasklist]
### EIP-7702
- [x] Nonce is no longer optional
- [x] Gas and validation changes https://github.com/ethereum/EIPs/pull/8766
- [ ] https://github.com/bluealloy/revm/pull/1695
```

```[tasklist]
### Engine API
- [ ] `engine_getBlobsV1` https://github.com/ethereum/execution-apis/pull/559/files
``` 

```[tasklist]
### EIP-2935
- [x] Move to system call (see https://github.com/ethereum/EIPs/pull/8816)
```
