### ISSUE TITLE
Tracking: In-memory compliance for `BlockchainProvider2`

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10186]
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10176
- [ ] https://github.com/paradigmxyz/reth/issues/10180
- [ ] https://github.com/paradigmxyz/reth/issues/10181
- [ ] https://github.com/paradigmxyz/reth/issues/10182
- [ ] https://github.com/paradigmxyz/reth/issues/10183
- [ ] https://github.com/paradigmxyz/reth/issues/10184
- [ ] https://github.com/paradigmxyz/reth/issues/10185
- [ ] https://github.com/paradigmxyz/reth/issues/10246
- [ ] https://github.com/paradigmxyz/reth/issues/10297
- [ ] https://github.com/paradigmxyz/reth/issues/10301
- [ ] https://github.com/paradigmxyz/reth/issues/10322
```

**Comment by malik672** [comment]
@Rjected assign me

**Comment by Rjected** [comment]
> @Rjected assign me

hi @malik672 , this is a tracking issue, do you mind picking one of the issues in the tasklist?

**Comment by malik672** [comment]
I know, can i pick them all

**Comment by Rjected** [comment]
> I know, can I pick them all and pull a pr for all of them at once

@malik672 It would be much easier to review them issue by issue, additionally there is already a WIP PR for https://github.com/paradigmxyz/reth/issues/10176. Feel free to submit PRs for the free issues!

**Comment by malik672** [comment]
> > I know, can I pick them all and pull a pr for all of them at once
> 
> @malik672 It would be much easier to review them issue by issue, additionally there is already a WIP PR for #10176. Feel free to submit PRs for the free issues!

same with #10246

**Comment by Rjected** [comment]
I think we've solved this

**Comment by Rjected** [comment]
whoops just saw the open issues
