### ISSUE TITLE
feat: relax `sync` constraint on Provider traits

### ISSUE THREAD

**Issue by greged93** [paradigmxyz/reth#10267]
### Describe the feature

For the progress of our work on an implementation of a Ethereum compliant RPC interface between Ethereum calls and a Starknet backend, we would like to be able to reuse the `EthApi` structure along with its `FullEthApi` implementation in order to adopt a more structured repository and avoid code duplication with Reth. 

Our current obstacle is that a lot of the `Provider` traits from Reth, which make up the `FullEthApi` trait, are currently sync. This is acceptable in the repo's context since it doesn't require the use of asynchronous calls for database access but is currently a blocker for us.

We have looked into using `spawn_blocking` combined with `block_on` in order to enter an asynchronous context in the sync trait, but are concerned that this will degrade our performances as all DB accesses will be affected.

The following traits have been identified as needing to be relaxed in order for us to fully use our async context:

```[tasklist]
### Tasks
- [ ] Migrate `BlockReaderIdExt` to `async` context
- [ ] Migrate `BlockNumReader` to `async` context
- [ ] Migrate `BlockHashReader` to `async` context
- [ ] Migrate `HeaderProvider` to `async` context
- [ ] Migrate `BlockIdReader` to `async` context
- [ ] Migrate `BlockReader` to `async` context
- [ ] Migrate `EvmEnvProvider` to `async` context
- [ ] Migrate `ReceiptProvider` to `async` context
- [ ] Migrate `AccountReader` to `async` context
- [ ] Migrate `StateProvider` to `async` context
- [ ] Migrate `TransactionsProvider` to `async` context
```

We can split this into a series of PR's which would each modify 1-2 traits in order to slowly incorporate this in the codebase if the issue is accepted.

### Additional context

- PR for scaffolding: https://github.com/kkrt-labs/kakarot-rpc/pull/1325
