### ISSUE TITLE
Tests for `BlockchainProvider2` methods that query in-memory state

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#10322]
We implemented querying both database and canonical in-memory state for most of the methods, but none of them are covered with tests. Some methods have quite complicated logic (esp. range queries), so we should cover them with tests.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10331
- [ ] https://github.com/paradigmxyz/reth/issues/10334
- [ ] https://github.com/paradigmxyz/reth/issues/10336
- [ ] https://github.com/paradigmxyz/reth/issues/10337
- [ ] https://github.com/paradigmxyz/reth/issues/10338
- [ ] https://github.com/paradigmxyz/reth/issues/10339
- [ ] https://github.com/paradigmxyz/reth/issues/10340
- [ ] https://github.com/paradigmxyz/reth/issues/10341
- [ ] https://github.com/paradigmxyz/reth/issues/10342
- [ ] https://github.com/paradigmxyz/reth/issues/10343
- [ ] https://github.com/paradigmxyz/reth/issues/10344
- [ ] https://github.com/paradigmxyz/reth/issues/10345
- [ ] https://github.com/paradigmxyz/reth/issues/10346
- [ ] https://github.com/paradigmxyz/reth/issues/10347
- [ ] https://github.com/paradigmxyz/reth/issues/10353
- [ ] https://github.com/paradigmxyz/reth/issues/10352
- [ ] https://github.com/paradigmxyz/reth/issues/10351
- [ ] https://github.com/paradigmxyz/reth/issues/10350
- [ ] https://github.com/paradigmxyz/reth/issues/10349
- [ ] https://github.com/paradigmxyz/reth/issues/10348
```
