### ISSUE TITLE
tracking: trie debugging tool

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#10405]
### Describe the feature

Create a tool for debugging state root errors. For two reth nodes 1) stable instance with valid root output and 2) unhealthy instance with invalid root output, create a tool that gathers enough information from stable node to triage the bug in unstable one.

The tool is supposed to retrieve the execution witness and pre-images for the `target` block where root mismatch has happened. Then it should diff the witness information from an unstable node against a stable one:
1) If they are different, the tool should compare the execution witnesses for the parent block:
    a) the tool should attempt the same process for the parent until it finds the highest ancestor with mismatched witness
    b) for the highest ancestor, the tool should unroll the witness into trie proofs and print them to stdout, leaf nodes should include key preimage and decoded values
    
2) If they are the same, the tool should take the execution and trie outputs of the block and compare them

The tool should be first implemented as CLI option for the new engine that would take in an RPC URL of a stable node.  

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10404
- [ ] https://github.com/paradigmxyz/reth/issues/10425
- [ ] https://github.com/paradigmxyz/reth/issues/10550
- [ ] https://github.com/paradigmxyz/reth/issues/10549
- [ ] https://github.com/paradigmxyz/reth/issues/10547
- [ ] https://github.com/paradigmxyz/reth/issues/10546
```

**Comment by shekhirin** [comment]
@rkrasiuk can this be closed? We have a basic version of the witness hook that's enough for our needs implemented, and we can iterate on it outside of this tracking issue.

**Comment by rkrasiuk** [comment]
good job @shekhirin @Rjected
