### ISSUE TITLE
Tracking PayloadBuilder API enhancements 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10435]
### Describe the feature

ref #10434

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10436
- [ ] https://github.com/paradigmxyz/reth/issues/10437
- [ ] https://github.com/paradigmxyz/reth/issues/10438
- [ ] https://github.com/paradigmxyz/reth/issues/10446
```
