### ISSUE TITLE
op-reth outputs less information than op-geth regarding requests

### ISSUE THREAD

**Issue by AntonieDavid** [paradigmxyz/reth#10464]
### Describe the bug

I've been testing the op-reth client on base mainnet and found some differences when comparing the results from the node running on op-reth to the results from a node running op-geth. 
Main issue here is that op-reth client doesn't behave exactly like op-geth when it comes to errors for various requests, op-reth giving less information for the `message` parameter.

### Steps to reproduce

- first request:

payload: `{"method": "eth_sendRawTransaction", "params": ["0x02f87182210547830f4240833ab04d825208947449061f45d7b39b3b80b4159286cd8682f60a3c87096bfaddf1c00080c080a093b87bd8122c1daaba521a62d2dd6094cf5e49d319f794b98e77b0710c1546dfa04556c9919658ef514600b656d8da40f1a118266f2221692a6b3bef2446de5df5"], "id": 51, "jsonrpc": "2.0"}`

- second request:
payload: `{"method": "eth_estimateGas", "params": [{"value": "0x96bfaddf1c000", "from": "0x889ebdac39408782b5165c5185c1a769b4dd3ce6", "to": "0x7449061f45d7b39b3b80b4159286cd8682f60a3c"}], "id": 44, "jsonrpc": "2.0"}`

### Node logs

```text
first request:
op-reth client
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "nonce too low"
  },
  "id": 51
}
op-geth client
{
  "jsonrpc": "2.0",
  "id": 51,
  "error": {
    "code": -32000,
    "message": "nonce too low: next nonce 72, tx nonce 71"
  }
}


second request:
op-reth client
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "insufficient funds for gas * price + value"
  },
  "id": 44
}
op-geth client
{
  "jsonrpc": "2.0",
  "id": 44,
  "error": {
    "code": -32000,
    "message": "failed with 50000000 gas: insufficient funds for gas * price + value: address 0x889eBDAc39408782B5165c5185C1A769B4Dd3ce6 have 1444840609176611 want 2652000000000000"
  }
}
```

### Platform(s)

Linux (x86)

### What version/commit are you on?

op-reth --version reth Version: 1.0.3 Commit SHA: https://github.com/paradigmxyz/reth/commit/390f30aadebcdd509e72cc04327c3b854de076a6 Build Timestamp: 2024-08-05T23:59:17.371843433Z Build Features: jemalloc,optimism Build Profile: maxperf

### What database version are you on?

op-reth db version
2024-08-22T18:23:51.766359Z INFO Initialized tracing, debug log directory: /root/.cache/reth/logs/optimism
Error: Datadir does not exist: "/root/.local/share/reth/optimism"

### Which chain / network are you on?

base mainnet

### What type of node are you running?

Archive (default)

### If you've built Reth from source, provide the full command you used

source "$HOME/.cargo/env" && RUSTFLAGS="-C target-cpu=native" cargo build --profile maxperf --features jemalloc,asm-keccak,optimism --bin op-reth

### Code of Conduct

- [X] I agree to follow the Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10498
- [ ] https://github.com/paradigmxyz/reth/issues/10732
```

**Comment by ShantelPeters** [comment]
Can I work on this ?

**Comment by emhane** [comment]
sure @ShantelPeters

**Comment by AntonieDavid** [comment]
Thanks for addressing this issue, did you make any progress on this @ShantelPeters ?

**Comment by emhane** [comment]
I'm mostly concerned about the error codes being different. nonetheless, seems like rollups and tests are relying on the message string rather than the code for now. in which spec repo would and issue be opened to sort out el rpc error codes?
