### ISSUE TITLE
Remove `optimism` feature from `reth-primitives`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#10515]
### Describe the feature

Remove `optimism` feature from `reth-primitives`

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10514
- [ ] https://github.com/paradigmxyz/reth/issues/9484
- [ ] https://github.com/paradigmxyz/reth/issues/10750
- [ ] https://github.com/paradigmxyz/reth/pull/6858
```

**Comment by ShantelPeters** [comment]
Please can I be assigned to this issue

**Comment by emhane** [comment]
this issue isn't complete yet @ShantelPeters, it's a tracking issue and more subtasks are yet to be added, can assign you to the subtask though if you like?

**Comment by mattsse** [comment]
I'm closing this in favor of #7649 where we can track next steps

**Comment by emhane** [comment]
reopening since easier to track on crate by crate basis since list is so long
