### ISSUE TITLE
Tracking: On-disk reorg handling

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#10570]
This tracks all of the things we need to do to properly handle on-disk reorgs in the new engine.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10552
- [ ] https://github.com/paradigmxyz/reth/issues/10558
- [ ] https://github.com/paradigmxyz/reth/pull/10551
- [ ] https://github.com/paradigmxyz/reth/issues/10572
```
