### ISSUE TITLE
Tracking issue primitive types abstraction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#10744]
### Describe the feature

supersedes #8721

```[tasklist]
- [ ] #10741
- [ ] https://github.com/paradigmxyz/reth/issues/10745
- [ ] https://github.com/paradigmxyz/reth/issues/8748
- [ ] https://github.com/paradigmxyz/reth/issues/8825
- [ ] https://github.com/paradigmxyz/reth/issues/9484
- [ ] https://github.com/paradigmxyz/reth/issues/10746
- [ ] #9554
- [ ] https://github.com/paradigmxyz/reth/issues/10747
- [ ] https://github.com/paradigmxyz/reth/issues/10751
- [ ] https://github.com/paradigmxyz/reth/issues/10909
```
