### ISSUE TITLE
Tracking: Devnet 4

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#11143]
### Describe the feature

These tasks are related to Pectra devnet 4.

See the [spec](https://notes.ethereum.org/@ethpandaops/pectra-devnet-4).

```[tasklist]
### Changes
- [x] EIP-6110: Flat request encoding
- [x] EIP-7251: Update bytecode
- [x] EIP-7251: Flat request encoding
- [x] EIP-7002: Flat request encoding
- [x] EIP-7685: Replace request root with flat request hash
- [x] EIP-7702: Additional validity constraints
- [x] Engine API: Merge requests into one opaque list
```

```[tasklist]
### Alloy changes
- [ ] https://github.com/alloy-rs/alloy/issues/1337
- [ ] https://github.com/alloy-rs/alloy/issues/1338
- [ ] https://github.com/alloy-rs/alloy/issues/1339
- [ ] https://github.com/alloy-rs/alloy/issues/1340
```

**Comment by onbjerg** [comment]
We're now devnet 4 ready
