### ISSUE TITLE
Tracking: Initial Sparse Trie + State Root Task 

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#11169]
## Description

The Performance Roadmap including all tasks for our [first perf release](https://github.com/paradigmxyz/reth/milestone/8?closed=1)  including State Root Task + Sparse Trie to increase performance for L1.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/10666
- [ ] https://github.com/paradigmxyz/reth/pull/10927
- [ ] https://github.com/paradigmxyz/reth/issues/11161
- [ ] https://github.com/paradigmxyz/reth/issues/10955
- [ ] https://github.com/paradigmxyz/reth/issues/11220
- [ ] https://github.com/paradigmxyz/reth/issues/11274
- [ ] https://github.com/paradigmxyz/reth/issues/11330
- [ ] https://github.com/paradigmxyz/reth/issues/12217
- [ ] https://github.com/paradigmxyz/reth/pull/13898
- [ ] https://github.com/paradigmxyz/reth/pull/14004
- [ ] https://github.com/paradigmxyz/reth/pull/14108
- [ ] https://github.com/paradigmxyz/reth/pull/13845
- [ ] https://github.com/paradigmxyz/reth/pull/14077
- [ ] https://github.com/paradigmxyz/reth/pull/13251
- [ ] https://github.com/paradigmxyz/reth/pull/14117
- [ ] https://github.com/paradigmxyz/reth/issues/14166
- [ ] https://github.com/paradigmxyz/reth/issues/14251
- [ ] https://github.com/paradigmxyz/reth/issues/14271
```

**Comment by jenpaff** [comment]
bullish!
