### ISSUE TITLE
Tracking: ExEx Write-Ahead-Log (WAL)

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#11200]
### Describe the feature

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/pull/10995
- [ ] https://github.com/paradigmxyz/reth/pull/11174
- [ ] https://github.com/paradigmxyz/reth/issues/11201
- [ ] https://github.com/paradigmxyz/reth/issues/11207
- [ ] https://github.com/paradigmxyz/reth/issues/10489
- [ ] https://github.com/paradigmxyz/reth/issues/11256
- [ ] https://github.com/paradigmxyz/reth/issues/11257
- [ ] https://github.com/paradigmxyz/reth/issues/11258
- [ ] https://github.com/paradigmxyz/reth/issues/11261
- [ ] https://github.com/paradigmxyz/reth/issues/11202
- [ ] https://github.com/paradigmxyz/reth/issues/11262
- [ ] https://github.com/paradigmxyz/reth/issues/11268
- [ ] https://github.com/paradigmxyz/reth/issues/11370
- [ ] https://github.com/paradigmxyz/reth/issues/11322
- [ ] https://github.com/paradigmxyz/reth/issues/11425
- [ ] https://github.com/paradigmxyz/reth/pull/11638
- [ ] https://github.com/paradigmxyz/reth/issues/11423
- [ ] https://github.com/paradigmxyz/reth/issues/11426
- [ ] https://github.com/paradigmxyz/reth/issues/11803
- [ ] https://github.com/paradigmxyz/reth-exex-examples/issues/25
```
