### ISSUE TITLE
Tracking: Legacy engine metrics

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#11225]
In https://github.com/paradigmxyz/reth/pull/11175 we are including `TreeMetrics` from the old engine, so the existing dashboard will still work. That PR only integrates one metric, because others are either not applicable, or are nontrivial to implement.

This is the `TreeMetrics` struct:
https://github.com/paradigmxyz/reth/blob/c78b5c9cc51337bdc7377f41a42f8e8bcae24fde/crates/blockchain-tree/src/metrics.rs#L8-L26

We should evaluate each metric in here, and either schedule it for removal when we make the new engine the default, or track its implementation progress.

```[tasklist]
### Tasks
- [ ] Sidechain count metric
- [x] [Canonical chain height](#11175)
- [x] Reorg count
- [ ] Latest reorg depth
- [ ] Longest sidechain height
- [ ] `trie_updates_insert_cached` - does this belong in this metric? Or should we create a trie specific engine metrics struct
- [ ] `trie_updates_insert_recomputed` - same question
```
