### ISSUE TITLE
SDK meta

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11241]
- A generalisation of the codebase in terms of injectable EVM rollup data primitives: block, block header, block body, signed transaction, transaction, transaction envelope type ID, and receipt. Required to extract OP as a library, as opposed to the current feature gated OP logic.

- Promotion of state root computation to an injectable component, in order to invite to parallel experimentation on state root computation performance by different projects.

```[tasklist]
### Tasks
- [ ] #11239
- [ ] https://github.com/paradigmxyz/reth/issues/9554
- [ ] https://github.com/paradigmxyz/reth/issues/7649
- [ ] https://github.com/paradigmxyz/reth/issues/11242
- [ ] https://github.com/paradigmxyz/reth/issues/11830
- [ ] https://github.com/paradigmxyz/reth/issues/12454
- [ ] https://github.com/paradigmxyz/reth/issues/12575
- [ ] https://github.com/paradigmxyz/reth/issues/12576
- [ ] https://github.com/paradigmxyz/reth/issues/13238
```

**Comment by emhane** [comment]
anything you can help out with here @clabby @refcell is much appreciated
