### ISSUE TITLE
Remove multi provider trait functions in rpc helper traits

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11422]
### Describe the feature

we compose various rpc traits with default impls

like:

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc-eth-api/src/helpers/trace.rs#L22-L22

these are effective stacked traits.
currently we have some functions multiple times:

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc-eth-api/src/helpers/trace.rs#L26-L26

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc-eth-api/src/helpers/call.rs#L459-L459

or 

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc-eth-api/src/helpers/transaction.rs#L56-L56

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc-eth-api/src/helpers/pending_block.rs#L47-L52

resulting in some inconvenient usage and restrictions.

like:

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc-eth-api/src/helpers/block.rs#L154-L154

ideally we only have one evm_config and one provider function, perhaps in a single trait that sits at the bottom of the stack, these should like by an associated type and we can easily implement this because we have this generic:

https://github.com/paradigmxyz/reth/blob/a07efa7b5b83b9821631a9191e225a8c0bc42f0b/crates/rpc/rpc/src/eth/helpers/transaction.rs#L13-L23

and it is expected that the final provider is then the full provider that satisfies all traits.

the stacked traits can then add the required bounds

```rust
trait EthCore // naming tbd {
  type Provider;
  type Evm;

  fn provider(&self) -> &Self::Provider;
  fn evm_config...
}
```

then we can force the required trait bounds on Trace for example

```rust
trait Trace: EthCore<Provider: ....> {

}
```

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/12050
- [ ] https://github.com/paradigmxyz/reth/pull/12094
- [ ] https://github.com/paradigmxyz/reth/pull/12095
- [ ] https://github.com/paradigmxyz/reth/pull/12098
- [ ] https://github.com/paradigmxyz/reth/pull/12100
- [ ] https://github.com/paradigmxyz/reth/pull/12104
- [ ] https://github.com/paradigmxyz/reth/pull/12102
- [ ] https://github.com/paradigmxyz/reth/pull/12109
- [ ] https://github.com/paradigmxyz/reth/pull/12121
- [ ] https://github.com/paradigmxyz/reth/pull/12122
```

**Comment by emhane** [comment]
something like this would be helpful: https://github.com/paradigmxyz/reth/pull/10616/files

then moving all the getters in `FullNodeComponents` to this trait. removing this redundancy at the price of making the the trait bounds less precise, isn't helpful. Some rollups won't use all the `FullProvider`, only certain providers. it's nice sdk if they don't have to do lots of noop impl of provider traits they aren't using on their provider type.

besides it makes it harder to build unit tests for this code, which we should aim to do despite hive test coverage.

**Comment by mattsse** [comment]
right, #10616 is more or less the unlock here
