### ISSUE TITLE
Remove build script from node-core

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#11767]
### Describe the feature

node-core contains a build script that sets various env vars such as:

https://github.com/paradigmxyz/reth/blob/7b1b1fcb3b632d8c877a3e761a77ae4d513c0c2a/crates/node/core/src/version.rs#L102-L108

this isn't great if we want to make this node specific, therefor this should be part of the cli abstraction or launch workflow

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/11766
- [ ] https://github.com/paradigmxyz/reth/issues/11768
- [ ] https://github.com/paradigmxyz/reth/issues/11770
```
