### ISSUE TITLE
Tracking: Dynamically Loaded ExExes

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#11917]
## Goal

Be able to add ExExes to a node without re-compiling the main Reth binary.

## Solution

Dynamically loaded ExExes that are pre-compiled for a specific Reth version and a target platform. They can be installed into the node by copying them into the `DATADIR/exex/libs` directory and restarting the node.

## Roadmap

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/11919
- [ ] https://github.com/paradigmxyz/reth/issues/11928
- [ ] https://github.com/paradigmxyz/reth/issues/11930
```
