### ISSUE TITLE
perf(engine): create standalone state root task

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#12053]
## Description

Create a standalone state root task that is spawned before block execution starts.

https://github.com/paradigmxyz/reth/blob/2fba3c027b7396db868b162e16635197cd584822/crates/engine/tree/src/tree/mod.rs#L2171-L2173

A task should initialize a blinded sparse and subscribe to transaction state stream. As it receives transaction execution results, it should fetch the proofs for relevant accounts from the database and reveal them to the tree.

Then it should update relevant leaves according to the result of the transaction.

A lot of things can be reused from https://github.com/paradigmxyz/reth/pull/11154.
```[tasklist]
### Tasks
- [x] Skeleton of state root task #12305
- [x] Integration with executor: the task subscribes to a stream of state updates from the executor #12316 #12335 #12378
- [x] Proof fetching for modified accounts #12403 #12413 #12467 #12510 #12458
- [ ] Sparse trie integration
```
