### ISSUE TITLE
Tracking: Improve `reth-trie-db` state traits

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#12216]
Currently we have the following for the `DatabaseProof`, `DatabaseStateRoot`, etc. traits:
https://github.com/paradigmxyz/reth/blob/fe53ec5be98e4d7c49c4dce645b11dfc81e94587/crates/trie/db/src/proof.rs#L17-L36

This can likely be rewritten as:
```rust
pub trait StatefulProof {
    /// Generates the state proof for target account based on [`TrieInput`].
    fn overlay_account_proof(
        &self,
        input: TrieInput,
        address: Address,
        slots: &[B256],
    ) -> Result<AccountProof, StateProofError>;

    /// Generates the state [`MultiProof`] for target hashed account and storage keys.
    fn overlay_multiproof(
        &self,
        input: TrieInput,
        targets: HashMap<B256, HashSet<B256>>,
    ) -> Result<MultiProof, StateProofError>;
}
```

Where the caller can have a `from_tx` method on the struct itself, instead of having one on the trait. The trait implementer is responsible for owning or managing a tx / tx ref.

```[tasklist]
### Tasks
- [ ] Improve `DatabaseProof` trait
- [ ] Improve `DatabaseStorageProof` trait
- [ ] Improve `DatabaseStateRoot` trait
- [ ] Improve `DatabaseStorageRoot` trait
- [ ] Improve `DatabaseTrieWitness` trait
```

**Comment by frisitano** [comment]
One thing to be mindful of here is that the `Database*` traits may need to be modified / extended as part of our ambitions with https://github.com/paradigmxyz/reth/issues/11830 so it would be wise to take that into account when scheduling/planning this work. I think it makes sense to do this refactor after we complete #11830.

**Comment by Rjected** [comment]
> One thing to be mindful of here is that the `Database*` traits may need to be modified / extended as part of our ambitions with #11830 so it would be wise to take that into account when scheduling/planning this work. I think it makes sense to do this refactor after we complete #11830.

Yep agreed, just noting this here to make sure we remember to do it after

**Comment by jenpaff** [comment]
@Rjected could you give me some context on this tracking issue? sounds like an opportunity to open up some gfi's

**Comment by Rjected** [comment]
@jenpaff just made some issues, should be clear what to do now
