### ISSUE TITLE
Generic data primitives into `reth-evm`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12358]
### Describe the feature

Make execution stage generic over receipt type with `NodePrimitives` generic. Specify trait bound `NodePrimitives::Receipt: reth_primitives_traits::Receipt` or use `FullNodePrimitives` in impl bodies (https://github.com/paradigmxyz/reth/pull/12331).

Blocked by https://github.com/paradigmxyz/reth/pull/12357

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10746
- [ ] https://github.com/paradigmxyz/reth/pull/12397
- [ ] https://github.com/paradigmxyz/reth/pull/12635
- [ ] https://github.com/paradigmxyz/reth/issues/12943
- [ ] https://github.com/paradigmxyz/reth/issues/12944
- [ ] https://github.com/paradigmxyz/reth/issues/12945
- [ ] https://github.com/paradigmxyz/reth/issues/12946
- [ ] https://github.com/paradigmxyz/reth/issues/12947
```
