### ISSUE TITLE
SDK - integration generic data primitives

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12454]
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/12578
- [ ] https://github.com/paradigmxyz/reth/issues/10747
- [ ] https://github.com/paradigmxyz/reth/issues/12662
- [ ] https://github.com/paradigmxyz/reth/issues/13322
- [ ] https://github.com/paradigmxyz/reth/issues/13329
- [ ] https://github.com/paradigmxyz/reth/issues/12536
- [ ] https://github.com/paradigmxyz/reth/issues/12358
- [ ] https://github.com/paradigmxyz/reth/issues/12517
- [ ] https://github.com/paradigmxyz/reth/issues/12754
- [ ] https://github.com/paradigmxyz/reth/issues/12820
- [ ] https://github.com/paradigmxyz/reth/issues/12922
```

**Comment by mattsse** [comment]
completed
