### ISSUE TITLE
Downloaders generic over data primitives

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12536]
### Describe the feature

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/12469
- [ ] https://github.com/paradigmxyz/reth/pull/12451
- [ ] https://github.com/paradigmxyz/reth/pull/12435
```
