### ISSUE TITLE
Alloy unification

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12576]
### Describe the feature

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/12519
- [ ] https://github.com/paradigmxyz/reth/issues/7238
- [ ] https://github.com/paradigmxyz/reth/issues/11449
- [ ] https://github.com/paradigmxyz/reth/issues/12606
- [ ] https://github.com/paradigmxyz/reth/issues/11510
- [ ] https://github.com/paradigmxyz/reth/issues/12318
- [ ] https://github.com/paradigmxyz/reth/issues/12701
- [ ] https://github.com/paradigmxyz/reth/issues/9267
- [ ] https://github.com/paradigmxyz/reth/issues/12251
- [ ] https://github.com/paradigmxyz/reth/issues/11914
- [ ] https://github.com/paradigmxyz/reth/issues/11798
- [ ] https://github.com/paradigmxyz/reth/issues/11781
- [ ] https://github.com/paradigmxyz/reth/issues/12390
- [ ] https://github.com/paradigmxyz/reth/issues/11723
- [ ] https://github.com/paradigmxyz/reth/issues/11220
- [ ] https://github.com/paradigmxyz/reth/issues/11211
- [ ] https://github.com/paradigmxyz/reth/issues/11208
- [ ] https://github.com/paradigmxyz/reth/issues/11199
- [ ] https://github.com/paradigmxyz/reth/issues/11127
- [ ] https://github.com/paradigmxyz/reth/issues/11082
- [ ] https://github.com/paradigmxyz/reth/issues/11067
- [ ] https://github.com/paradigmxyz/reth/issues/11046
- [ ] https://github.com/paradigmxyz/reth/issues/10750
- [ ] https://github.com/paradigmxyz/reth/issues/10687
- [ ] https://github.com/paradigmxyz/reth/issues/10509
- [ ] https://github.com/paradigmxyz/reth/issues/10522
- [ ] https://github.com/paradigmxyz/reth/issues/10494
- [ ] https://github.com/paradigmxyz/reth/issues/10632
- [ ] https://github.com/paradigmxyz/reth/issues/10452
- [ ] https://github.com/paradigmxyz/reth/issues/10451
- [ ] https://github.com/paradigmxyz/reth/issues/9484
- [ ] https://github.com/paradigmxyz/reth/issues/9114
```

**Comment by jmcph4** [comment]
Thoughts on exposing a method in the `NodeBuilder` API that produces an Alloy [`Provider`](https://docs.rs/alloy/0.7.2/alloy/providers/trait.Provider.html)? One use case is making contract calls directly from an in-process context.

If there's already a solution for this then obviously disregard this note - but I must've missed it if it exists.

**Comment by mattsse** [comment]
marking this as completed

**Comment by gakonst** [comment]
Huge!
