### ISSUE TITLE
Tracking data primitive abstraction improvements

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12575]
### Describe the feature

Tracking modifications to `reth-primitives-traits` for usability in integration of generic data primitives throughout reth (ref  https://github.com/paradigmxyz/reth/issues/12454 )

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/12325
- [ ] https://github.com/paradigmxyz/reth/issues/12544
- [ ] https://github.com/paradigmxyz/reth/pull/12660
- [ ] https://github.com/paradigmxyz/reth/issues/12680
- [ ] https://github.com/paradigmxyz/reth/issues/12571
- [ ] https://github.com/paradigmxyz/reth/pull/12450
- [ ] https://github.com/paradigmxyz/reth/pull/12721
- [ ] https://github.com/paradigmxyz/reth/pull/12437
- [ ] https://github.com/paradigmxyz/reth/issues/11484
- [ ] https://github.com/paradigmxyz/reth/pull/12584
- [ ] https://github.com/paradigmxyz/reth/pull/12577
- [ ] https://github.com/paradigmxyz/reth/issues/12589
- [ ] https://github.com/paradigmxyz/reth/pull/12613
- [ ] https://github.com/paradigmxyz/reth/pull/12614
- [ ] https://github.com/paradigmxyz/reth/issues/12471
- [ ] https://github.com/paradigmxyz/reth/issues/12582
- [ ] https://github.com/paradigmxyz/reth/pull/12683
- [ ] https://github.com/paradigmxyz/reth/pull/12723
```

**Comment by mattsse** [comment]
marking this as closed now
