### ISSUE TITLE
`reth-provider` generic data primitives

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12754]
### Describe the feature

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/issues/12753
- [ ] https://github.com/paradigmxyz/reth/pull/12837
- [ ] https://github.com/paradigmxyz/reth/pull/12794
- [ ] https://github.com/paradigmxyz/reth/pull/12764
- [ ] https://github.com/paradigmxyz/reth/pull/12785
- [ ] https://github.com/paradigmxyz/reth/pull/12892
- [ ] https://github.com/paradigmxyz/reth/pull/12890
```
