### ISSUE TITLE
Generic data prims `reth-engine-tree`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#12922]
### Describe the feature

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/issues/12920
- [ ] https://github.com/paradigmxyz/reth/issues/12939
- [ ] https://github.com/paradigmxyz/reth/issues/12938
- [ ] https://github.com/paradigmxyz/reth/issues/12941
- [ ] https://github.com/paradigmxyz/reth/issues/12942
- [ ] https://github.com/paradigmxyz/reth/issues/13243
- [ ] https://github.com/paradigmxyz/reth/issues/13244
```
