### ISSUE TITLE
Tracking: Shanghai Support

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#1295]
### Describe the feature

This is a tracking issue to add [Shanghai](https://decrypt.co/resources/what-is-ethereums-shanghai-upgrade) support to reth. 

# Tasks

```[tasklist]
* [x] Add `Withdrawals` field to [P2P BlockBody](https://github.com/ethereum/go-ethereum/commit/2a2b0419fb966c54fb86b17bbccea743a45b4d2a#diff-3210763abf230e7f0fce7f0cd739a8ffa253599c6480aa34075017a4e310cd1cR239)
* [ ] https://github.com/paradigmxyz/reth/issues/1297
* [ ] https://github.com/paradigmxyz/reth/issues/1300
* [ ] https://github.com/paradigmxyz/reth/issues/1298
* [ ] https://github.com/paradigmxyz/reth/issues/1299
* [ ] https://github.com/bluealloy/revm/issues/370
* [ ] https://github.com/bluealloy/revm/issues/371
* [ ] https://github.com/bluealloy/revm/issues/372
* [ ] https://github.com/bluealloy/revm/issues/373 
```

### Additional context

* All Shanghai-related Geth changes: https://github.com/search?q=repo%3Aethereum%2Fgo-ethereum+shanghai&type=pullrequests
* Engine API Changes Spec: [EIP-4895: Beacon chain push withdrawals as operations](https://eips.ethereum.org/EIPS/eip-4895)

* Relevant PRs in other clients ([source](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md))

 EIP            | [EIP-3651](https://eips.ethereum.org/EIPS/eip-3651)                   | [EIP-3855](https://eips.ethereum.org/EIPS/eip-3855)                   | [EIP-3860](https://eips.ethereum.org/EIPS/eip-3860)                   | [EIP-4895](https://eips.ethereum.org/EIPS/eip-4895)                                                                        |
|----------------|-----------------------------------------------------------------------|-----------------------------------------------------------------------|-----------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------|
| **Geth**       | [Merged](https://github.com/ethereum/go-ethereum/pull/25819)          | [Merged](https://github.com/ethereum/go-ethereum/pull/24039)          | [Merged](https://github.com/ethereum/go-ethereum/pull/23847)      | [Merged](https://github.com/ethereum/go-ethereum/pull/26484)                                                           |
| **Besu**       | [Merged](https://github.com/hyperledger/besu/pull/4620)               | [Merged](https://github.com/hyperledger/besu/pull/4660)               | [Merged](https://github.com/hyperledger/besu/pull/4726)               | [Merged](https://github.com/hyperledger/besu/pull/4968)                                                                |
| **Nethermind** | [Merged](https://github.com/NethermindEth/nethermind/pull/4594)       | [Merged](https://github.com/NethermindEth/nethermind/pull/4599)       | [Merged](https://github.com/NethermindEth/nethermind/pull/4740)       | [Merged](https://github.com/NethermindEth/nethermind/pull/4731)                                                        |
| **Erigon**     | [Merged](https://github.com/ledgerwatch/erigon/pull/5745)             | [Merged](https://github.com/ledgerwatch/erigon/pull/5256)             | Merged ([1](https://github.com/ledgerwatch/erigon/pull/5892), [2](https://github.com/ledgerwatch/erigon/pull/6499))             | Merged ([1](https://github.com/ledgerwatch/erigon/pull/6009), [2](https://github.com/ledgerwatch/erigon/pull/6180), [3](https://github.com/ledgerwatch/erigon/pull/6496)) |
| **EthereumJS** | [Merged](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1814) | [Merged](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1616) | [Merged](https://github.com/ethereumjs/ethereumjs-monorepo/pull/1619) | [Merged](https://github.com/ethereumjs/ethereumjs-monorepo/pull/2353)                                                      |

**Comment by gakonst** [comment]
Closing - looks like we're g2g
