### ISSUE TITLE
Tracking: Receipt Generics

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#13137]
Right now we have the `ReceiptEnvelope` in alloy, and a corresponding type in op-alloy, that we must use once we try to remove the op feature flag from the codebase. This requires some work to properly wire / support:

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/13138
- [ ] Make eth-wire-types `Receipts` generic over `T` or replace with alloy `Receipts`
- [ ] Move provider implementations to set `Receipt` associated type to alloy `ReceiptEnvelope`
- [ ] https://github.com/paradigmxyz/reth/issues/13139
- [ ] https://github.com/paradigmxyz/reth/pull/13088
```
