### ISSUE TITLE
Tracking: Isthmus

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#13145]
### Describe the feature

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/pull/14441
- [ ] https://github.com/paradigmxyz/reth/pull/14307
- [ ] https://github.com/paradigmxyz/reth/pull/14464
```

**Comment by emhane** [comment]
implementation done, tracking testing in https://github.com/paradigmxyz/reth/issues/14777
