### ISSUE TITLE
discv5 support

### ISSUE THREAD

**Issue by rkrasiuk** [paradigmxyz/reth#1383]
### Describe the feature

Integrate https://github.com/sigp/discv5.

~~Optionally, allow downstreaming invalid messages to other protocol (discv4).~~
Ref https://github.com/ethereum/go-ethereum/pull/26699

## TODO
* add Stream wrapper type for the discv5 service that emits events, similar to : https://github.com/paradigmxyz/reth/blob/64e3a57dd98b8c9e9ed97f40a433e3d2ee90b925/crates/net/dns/src/lib.rs#L359-L366
* See how `Discovery` uses the discovery services: https://github.com/paradigmxyz/reth/blob/64e3a57dd98b8c9e9ed97f40a433e3d2ee90b925/crates/net/network/src/discovery.rs#L30-L35

The way this works is:
* Networkconfig gets discv5 config
* `Discovery::new` gets the config and _spawns_ service that should emit discovered entries back to `Discovery`

This discv5 support can be separate crate
```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/6151
- [ ] https://github.com/paradigmxyz/reth/pull/7328
- [ ] https://github.com/paradigmxyz/reth/pull/7336
- [ ] https://github.com/paradigmxyz/reth/pull/7394
- [ ] https://github.com/paradigmxyz/reth/pull/7446
- [ ] https://github.com/paradigmxyz/reth/pull/7458
- [ ] https://github.com/paradigmxyz/reth/pull/7461
```

**Comment by GrapeBaBa** [comment]
can I try this?

**Comment by PatStiles** [comment]
I am game to take this on

**Comment by yash-atreya** [comment]
@mattsse I can take this

**Comment by emhane** [comment]
is the `fork_id` field of the enr how `DnsDiscoveryService` knows that an enr is EL and not CL? or how else is that being done?

**Comment by emhane** [comment]
https://github.com/paradigmxyz/reth/pull/6151 is syncing base mainnet in 9 hours with `--debug.tip` flag. pr is being broken down into smaller prs for easier review.
