### ISSUE TITLE
Tracking: Hive test failures

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#1579]
Hive tests are being integrated into CI in #1348, and current results can be viewed in the PR's actions runs:
https://github.com/paradigmxyz/reth/actions/runs/4272628614

This issue tracks the current test suites, as well as blocking issues that prevent test suites from passing.

```
### `ethereum/engine`
```
moved to #2625

```[tasklist]
### `ethereum/rpc-compat`
- [ ] https://github.com/ethereum/go-ethereum/pull/26756
- [ ] https://github.com/ethereum/execution-apis/issues/386
- [ ] https://github.com/paradigmxyz/reth/issues/1777
- [ ] https://github.com/paradigmxyz/reth/issues/1781
- [ ] https://github.com/paradigmxyz/reth/issues/1782
- [ ] https://github.com/paradigmxyz/reth/issues/1785
- [ ] https://github.com/paradigmxyz/reth/issues/1784
- [ ] https://github.com/paradigmxyz/reth/issues/1783
- [ ] https://github.com/paradigmxyz/reth/issues/1907
- [ ] https://github.com/paradigmxyz/reth/issues/1905
- [ ] https://github.com/paradigmxyz/reth/issues/1906
- [ ] https://github.com/paradigmxyz/reth/issues/1898
- [ ] https://github.com/paradigmxyz/reth/issues/1951
- [ ] https://github.com/paradigmxyz/reth/issues/2033
- [ ] https://github.com/paradigmxyz/reth/issues/2042
- [ ] https://github.com/paradigmxyz/reth/issues/2043
- [ ] https://github.com/paradigmxyz/reth/issues/2046
- [ ] `debug_` failures (to track
```

```[tasklist]
### `ethereum/rpc`
- [ ] https://github.com/paradigmxyz/reth/issues/1225
- [ ] #1583
```

```[tasklist]
### `ethereum/sync`
- [ ] https://github.com/paradigmxyz/reth/issues/1580
- Resolved by creating a separate actions job that hard-codes the chain tip
- [ ] https://github.com/paradigmxyz/reth/issues/2044
```

```[tasklist]
### `devp2p/discv4`
 - [x] Passes
```

```[tasklist]
### `devp2p/eth`
 - [x] Announcement tests failing - should exclude announcement tests in #1348
 - [ ] #1582
 - [ ] #1581
- [ ] https://github.com/paradigmxyz/reth/issues/2030
```

```[tasklist]
### `smoke/network`
 - [x] Passes
```

```[tasklist]
### `smoke/genesis`
- [ ] #1530
- [ ] #1489
```
