### ISSUE TITLE
Tracking issue payload building improvements

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2401]
### Describe the feature

- [x] cache state reads #2381 
- [x] simplify/unify sealing process (withdrawals, sealing): add helper type
- [x] test coverage
- [x] skip invalid transactions
- [x] use correct state and parent
