### ISSUE TITLE
Tracking: Hive engine API failures

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#2625]
### Describe the feature

Extracted from #[1579](https://github.com/paradigmxyz/reth/issues/1579) specifically for `engine` hive tests

```[tasklist]
### `ethereum/engine`
- [ ] #1578
- [ ] #1587
- [ ] https://github.com/paradigmxyz/reth/issues/1614
- [ ] https://github.com/paradigmxyz/reth/issues/1675
- [ ] https://github.com/paradigmxyz/reth/issues/1676
- [ ] https://github.com/paradigmxyz/reth/issues/1746
- [ ] https://github.com/paradigmxyz/reth/issues/2515
- [ ] https://github.com/paradigmxyz/reth/issues/2542
- [ ] https://github.com/paradigmxyz/reth/issues/2673
- [ ] https://github.com/paradigmxyz/reth/issues/2680
- [ ] https://github.com/paradigmxyz/reth/issues/2751
- [ ] https://github.com/paradigmxyz/reth/issues/2815
- [ ] https://github.com/paradigmxyz/reth/issues/2839
- [ ] https://github.com/paradigmxyz/reth/issues/2944
- [ ] https://github.com/paradigmxyz/reth/issues/2846
- [ ] https://github.com/paradigmxyz/reth/issues/2947
- [ ] https://github.com/paradigmxyz/reth/issues/2955
- [ ] https://github.com/paradigmxyz/reth/issues/2956
- [ ] https://github.com/paradigmxyz/reth/issues/3007
- [ ] https://github.com/paradigmxyz/reth/issues/3057
- [ ] https://github.com/paradigmxyz/reth/issues/3058
- [ ] https://github.com/paradigmxyz/reth/issues/4809
- [ ] https://github.com/paradigmxyz/reth/issues/4810
- [ ] https://github.com/paradigmxyz/reth/issues/4586
```

**Comment by mattsse** [comment]
I think this has outlived its usefulness and any new failing hive tests should be tracked individually
