### ISSUE TITLE
Replace database helpers with helper functions

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2889]
## Background

We have different helpers for writing and reading things from the database, for example:

- `StateProvider` (trait) to read storage
- `AccountProvider` (trait) to read accounts
- `HeaderProvider` (trait) to read headers
- etc.

Some of these are implemented for `Transaction` (the struct in `reth-provider`), some are implemented for other in-memory temporary structures etc.

For interacting with the database we have the raw transactions (`DbTx`/`DbTxMut` traits), a wrapper around these (`Transaction`) and `ShareableDatabase` for sharing a database and opening/managing multiple transactions (usually read only ones).

## Problem

Currently some helpers are only implemented on `ShareableDatabase` and on `Transaction`. Ideally, we would be able to get rid of `Transaction` altogether, since it is a historical quirk of a lifetime issue we once had with the pipeline. The helpers should instead be for `DbTx`/`DbTxMut`.

`ShareableDatabase` also has some helpers that are not present elsewhere; ideally, these should be lifted out and moved to `DbTx`/`DbTxMut` as well.

However, the provider traits *and* the helper functions on `Transaction`/`ShareableDatabase` all share similar issues: either they open a new transaction on every call of every function (`ShareableDatabase`) or they open new cursors instead of reusing them (`Transaction`).

## Proposed solution

1. Get rid of `Transaction` to whatever extent possible
2. Create write-sided helpers (most of the helpers on `Transaction`) and/or "write provider" traits
3. Move the core helpers into functions that take a `DbTx` or `DbTxMut` or a cursor (where appropriate)
4. Add new helpers (where appropriate) to e.g. `HeaderProvider`/`BlockProvider`/`AccountProvider`
5. Rewrite the helpers in the provider traits to use the helper functions

## Reasoning

1. To reduce friction since some code takes `Transaction` when you only have a `DbTx` (which means you have to wrap it)
2. Some writes are shared for the pipeline and the blockchain tree, so it makes sense to have write helpers too to reduce code duplication (and therefore maintenance burden)
3. This solves the issue of opening multiple transactions/cursors for performance critical code; instead of using the provider traits, they could use the functional style helpers. Some provider traits could also reuse the transactions/cursors internally using this mechanism
4. Some of our current helpers logically live in these traits, so they should be here naturally
5. To reduce code duplication

## Example

https://github.com/paradigmxyz/reth/pull/2880 moves some helpers in `ShareableDatabase` into functions that re-use transactions

```[tasklist]
## Tasks
- [ ] Create new modules in `reth-provider` called `readers` (read fns) and `writers` (write fns) (maybe?)
- [ ] Add account readers (see [`AccountProvider`](https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/account.rs))
- [ ] Add block readers (see [`BlockProvider`](https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/block.rs))
- [ ] Add header readers (see [`HeaderProvider`](https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/header.rs))
- [ ] Add receipt readers (see [`ReceiptProvider`](https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/receipts.rs))
- [ ] Add state readers (see [`StateProvider`](https://github.com/paradigmxyz/reth/blob/main/crates/storage/provider/src/traits/state.rs))
- [ ] (Todo) spec out writers/remaining readers
``` 

### Additional context

See https://github.com/paradigmxyz/reth/pull/2880#discussion_r1209198848

**Comment by onbjerg** [comment]
cc @gakonst @rkrasiuk @joshieDo @rakita @mattsse thoughts?

**Comment by onbjerg** [comment]
Assigned me and joshie - for now, this is not super actionable before I get some feedback. Joshie is assigned since he is currently working on cleaning up these parts anyway, and I will take point on speccing this out if we agree it's a good idea

**Comment by joshieDo** [comment]
I was thinking of `ShareableDatabase` as a core component in which every implemented provider would be able to utilize the same `DbTx` if necessary ([example](https://github.com/paradigmxyz/reth/compare/shareabledb/tx?expand=1#diff-224951349b50783e1a0937cee094e55dfa0c817770001a48d84c02627ccbb739)). And unless **really** necessary, every helper/standalone function should ideally be part of a provider (isn't that the point?). I feel, like otherwise we'll keep duplicating code,  as it is the case on 2880 with `header_by_number`.

**Comment by onbjerg** [comment]
Closing this as per our sync and opening up new issues with what we landed on
