### ISSUE TITLE
Tracking: EIP-4844

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2893]
### Describe the feature

Tracking issue for [EIP-4844: Shard Blob Transactions](https://eips.ethereum.org/EIPS/eip-4844)

These are from the devnet-6 testnet spec [found here](https://notes.ethereum.org/@bbusa/dencun-devnet-6)

```[tasklist]
### Primitives
- [ ] https://github.com/paradigmxyz/reth/issues/3941
- [ ] https://github.com/paradigmxyz/reth/pull/4085
- [x] Add `verify_kzg_proof` (single proof) and `verify_kzg_proofs` (multiple proofs) - included in `c-kzg`
- [ ] https://github.com/paradigmxyz/reth/issues/3746
```

Relevant documents:

- [Polynomial commitment helpers](https://github.com/ethereum/consensus-specs/blob/86fb82b221474cc89387fa6436806507b3849d88/specs/deneb/polynomial-commitments.md#verify_blob_kzg_proof_batch), specifically `verify_blob_kzg_proof` and `verify_blob_kzg_proof_batch`

```[tasklist]
### Execution
- [ ] https://github.com/bluealloy/revm/issues/526
``` 

```[tasklist]
### Calculations/Consensus
- [x] Add `calc_excess_data_gas` to calculate `excess_data_gas`
- [ ] Add dummy fork for EIP-4844 testing
```

Relevant PRs:

- https://github.com/ethereum/EIPs/pull/7062: This PR adds `data_gas_used` to the header (in addition to the pre-existing 4844 field `excess_data_gas`)
- https://github.com/ethereum/EIPs/pull/7038: Reorders the RLP encoding of blob transactions
- https://github.com/ethereum/EIPs/pull/7020: Note on the precompile inputs (`z` and `y`) being big endian

```[tasklist]
### Engine API
- [x] Support `engine_newPayloadV3`
- [x] Support `engine_getPayloadV3`
- [x] Support `engine_forkchoiceUpdatedV3`
```

Relevant documents: 

- [Engine API blob extension spec](https://github.com/ethereum/execution-apis/blob/main/src/engine/experimental/blob-extension.md)

Relevant PRs:

- https://github.com/ethereum/execution-apis/pull/404: Limits the number of blobs in `BlobsBundleV1` to `MAX_BLOBS_PER_BLOCK`
- https://github.com/ethereum/execution-apis/pull/398: Adds `dataGasUsed` and `dataGasPrice` to receipts for EIP-4844 transactions

```[tasklist]
### Networking
- [x] Add support for blob transactions
- [x] newpooledtransaction changes https://eips.ethereum.org/EIPS/eip-5793
- [ ] https://github.com/paradigmxyz/reth/issues/3944
```

Relevant documents:

- [Networking section](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#networking) of the EIP

```[tasklist]
### Transaction pool
- [x] Add blob transaction ordering by new blob gas/fees fields
- [x] Add blob transaction validation
```

Relevant documents:

- [Networking section](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md#networking) of the EIP

```[tasklist]
### Tests
- [x] Support the engine API blob tests in hive
```

```[tasklist]
## TODOS
- [x] Add `TxEip4844` to the Transaction enum
- [x] Additional gas/fee functions for blobs
- [x] Additional optional block data (similar to withdrawals): excessDataGas, dataGasUsed
- [x] RPC type updates: add optional extra fields, versioned hashes, blob gas fee cap
- [x] engine API V3 updates: Blobsbundle
- [x] Additional consensus checks
- [x] EIP4844 support in txpool
- [x] forkid/cancun timestamps
- [x] new transaction errors similar to dynamic fee: "max fee per data gas too low", "max blobs/data reached"
- [x] network/download changes: custom propagation sqrt peers is too big
- [ ] https://github.com/paradigmxyz/reth/issues/3929
```

Relevant PRs:

- https://github.com/ethereum/hive/pull/759

**Comment by 0xJepsen** [comment]
I have been working the parts of this in revm here https://github.com/bluealloy/revm/pull/536
I have a full implementation i did with akworks in the "point_evaluation_old" and just pushed an updated version with the c-kzg ffi bindings that the EF audited here: https://github.com/ethereum/c-kzg-4844/tree/main/bindings/csharp

**Comment by 0xJepsen** [comment]
You can grab the primitive you want from either implementations if you like or just use as an example. Where should they fit in the reth architecture? I'm happy to add them.

**Comment by tcoratger** [comment]
Item add `TxEip4844` to the `Transaction` enum should be closed with #3953 no?

**Comment by mattsse** [comment]
completed
