### ISSUE TITLE
Tracking: Cancun

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2894]
### Describe the feature

Tracking issue for devnet 6.

Slated for end June/July

```[tasklist]
## EIPs
- [ ] https://github.com/paradigmxyz/reth/issues/2893
- [ ] https://github.com/paradigmxyz/reth/issues/2895
- [ ] https://github.com/bluealloy/revm/issues/524
- [ ] https://github.com/bluealloy/revm/issues/523
- [ ] https://github.com/bluealloy/revm/issues/154
```

```[tasklist]
## External issues
- [ ] https://github.com/bluealloy/revm/issues/527
```

### Additional context
Ref https://github.com/ethereum/execution-apis/pull/420

See also [the spec](https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/cancun.md#included-eips)

**Comment by onbjerg** [comment]
Note on EIP-1153 (transient storage), EIP-5656 (MCOPY) and EIP-6780, these all seem to only need work done in revm, so they are not tracked here

**Comment by 0xJepsen** [comment]
@rakita when would be a good time to work on this in revm, I'm happy to follow your guidance. I would love to work on this if not just to learn.

**Comment by rakita** [comment]
Added tracking list to revm: https://github.com/bluealloy/revm/issues/527

**Comment by onbjerg** [comment]
Added it to the tasklist so it auto-tracks when they are done @rakita 😄
