### ISSUE TITLE
Tracking: EIP-4788

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#2895]
### Describe the feature

Tracking issue for [EIP-4788](https://github.com/ralexstokes/EIPs/blob/master/EIPS/eip-4788.md).

```[tasklist]
## Primitives
- [ ] Add `hash_tree_root` to `Header` (32 bytes)
- [ ] Add `current_slot` to `Header` (big endian u64)
```

Note:

- The new header fields are added after the new header fields in EIP-4844 (see [this section](https://github.com/ralexstokes/EIPs/blob/master/EIPS/eip-4788.md#block-structure-and-validity))

```[tasklist]
## Execution
- [ ] https://github.com/bluealloy/revm/issues/525
```

Note:

- The beacon root written to the contract has a particular structure and may be in multiple slots on the contract, see [this section](https://github.com/ralexstokes/EIPs/blob/master/EIPS/eip-4788.md#block-processing)

```[tasklist]
## Consensus
- [x] Add dummy fork to enable EIP
```
