### ISSUE TITLE
Tracking: Blockchain Tree Metrics

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3283]
### Describe the feature

Currently there are no metrics in the blockchain tree, which means there is zero observability into how reth is behaving during live-sync. Pipeline sync on the other hand is well instrumented.

Here are some things we should add metrics for:
```[tasklist]
### Tasks
- [x] Blockchain tree buffer size
- [x] Number of sidechains
- [x] Canonical chain depth and tip number
- [ ] https://github.com/paradigmxyz/reth/issues/3814
- [ ] https://github.com/paradigmxyz/reth/issues/3817
- [ ] https://github.com/paradigmxyz/reth/issues/3815
- [ ] https://github.com/paradigmxyz/reth/issues/3816
```

There could be others, so feel free to suggest things that might be useful

**Comment by int88** [comment]
I'd like to complement these metrics, if no one has already started to do it. @Rjected @onbjerg

**Comment by Rjected** [comment]
@int88 I just converted the remaining tasks into issues so we can track their progress. Let me know which one you'd like to take!

**Comment by Rjected** [comment]
Closing as we have basically only one thing left for this
