### ISSUE TITLE
Tracking: Crate examples

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#3392]
### Describe the feature

This is a tracking issue for crate usage examples we would like to add to illustrate how you can use reth as a library.

```[tasklist]
### P2P
- [ ] https://github.com/paradigmxyz/reth/issues/3393
- [ ] https://github.com/paradigmxyz/reth/issues/3394
```

```[tasklist]
### DB
- [ ] https://github.com/paradigmxyz/reth/issues/3395
- [ ] https://github.com/paradigmxyz/reth/issues/3396
```

```[tasklist]
### RPC
- [ ] https://github.com/paradigmxyz/reth/issues/3397
- [ ] https://github.com/paradigmxyz/reth/issues/3398
```

```[tasklist]
### Txpool
- [ ] https://github.com/paradigmxyz/reth/issues/3399
- [ ] https://github.com/paradigmxyz/reth/issues/3400
```

```[tasklist]
### Payload building
- [ ] https://github.com/paradigmxyz/reth/issues/3401
```
