### ISSUE TITLE
Tracking: Pruning

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3428]
### Describe the feature

Tracking issue for pruning.

```[tasklist]
## Common
- [ ] https://github.com/paradigmxyz/reth/issues/3430
- [ ] https://github.com/paradigmxyz/reth/issues/3581
- [ ] https://github.com/paradigmxyz/reth/issues/3960
```

```[tasklist]
## Pipeline
- [ ] https://github.com/paradigmxyz/reth/issues/3433
- [ ] https://github.com/paradigmxyz/reth/issues/3434
- [ ] https://github.com/paradigmxyz/reth/issues/3557
- [ ] https://github.com/paradigmxyz/reth/issues/3558
- [ ] https://github.com/paradigmxyz/reth/issues/3559
```

```[tasklist]
## Database Provider
- [ ] https://github.com/paradigmxyz/reth/issues/3432
```

```[tasklist]
## Blockchain Tree
- [ ] https://github.com/paradigmxyz/reth/issues/3560
- [ ] https://github.com/paradigmxyz/reth/issues/3561
- [ ] https://github.com/paradigmxyz/reth/issues/3938
```

```[tasklist]
## Pruner
- [ ] https://github.com/paradigmxyz/reth/issues/3439
- [ ] https://github.com/paradigmxyz/reth/issues/3692
- [ ] https://github.com/paradigmxyz/reth/issues/3694
- [ ] https://github.com/paradigmxyz/reth/issues/3695
- [ ] https://github.com/paradigmxyz/reth/issues/3696
- [ ] https://github.com/paradigmxyz/reth/issues/3697
- [ ] https://github.com/paradigmxyz/reth/issues/4011
```

```[tasklist]
## RPC
- [ ] https://github.com/paradigmxyz/reth/issues/4056
- [ ] https://github.com/paradigmxyz/reth/issues/4057
```

### Additional context

Previous related discussion and latest decision on the design: https://github.com/paradigmxyz/reth/issues/2629#issuecomment-1589365648
