### ISSUE TITLE
Tracking: discovery quality metrics

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3665]
### Describe the feature

I was very impressed by https://github.com/ethereum/go-ethereum/pull/27621 and thought it would be a good idea for us to replicate some of these metrics. This tracks what we would need to add in reth, and what we would need to add in the existing grafana dashboard. Each of these tasks are likely small, so anyone who would like to take one should let me know, and I'll create an issue to track the individual task!

## Discovery

We would need an additional metric for nodes in kbuckets, and graph in grafana:
```[tasklist]
### Discovery Metrics
- [ ] `discover/bucket/{index}/count` - the number of nodes in bucket index
- [ ] Dashboard for the kbuckets metric
```

## `eth` handshake

We would need to create metrics for `eth` handshake errors that map to these:
```[tasklist]
### Eth protocol metrics
- [ ] `eth/protocols/eth/{ingress|egress}/handshake/error/peer` - unexpected peer behavior
- [ ] `eth/protocols/eth/{ingress|egress}/handshake/error/timeout` - handshake timeout
- [ ] `eth/protocols/eth/{ingress|egress}/handshake/error/network` - wrong network id
- [ ] `eth/protocols/eth/{ingress|egress}/handshake/error/version` - wrong protocol version
- [ ] `eth/protocols/eth/{ingress|egress}/handshake/error/genesis` - wrong genesis
- [ ] `eth/protocols/eth/{ingress|egress}/handshake/error/forkid` - wrong forkid
```

## `p2p` dials

We already have some error metrics:
https://github.com/paradigmxyz/reth/blob/526f624e1cbfd659184873bffe12ec602678b57f/crates/net/network/src/metrics.rs#L64-L110

So we should make sure that the error metrics are in the grafana dashboard and named appropriately, and add the metrics which we don't already have:
```[tasklist]
### P2P dial metrics
- [ ] `p2p/dials/success` - the total number of dials that result in a peer being added to the peerset
- [ ] `p2p/dials/error/connection` - unable to initiate TCP connection to target
- [ ] `p2p/dials/error/saturated` - local client is already connected to its maximum number of peers
- [ ] `p2p/dials/error/known` - dialing an already connected peer
- [ ] `p2p/dials/error/self` - dialing the local node's id
- [ ] `p2p/dials/error/useless` - dialing a peer that doesn't share an capabilities with the local node
- [ ] `p2p/dials/error/id/unexpected` - dialed peer repsoned with different id than expected
- [ ] `p2p/dials/error/rlpx/enc` - error negotiating the rlpx encryption during dial
- [ ] `p2p/dials/error/rlpx/proto` - error during rlpx protocol handshake`
``` 
Out of these, I don't think we have a metric similar to `p2p/dials/success`.

## Grafana
In addition to these, it would be nice to create a graph similar to the `Dial Quality` graph from the original PR:
![image](https://github.com/ethereum/go-ethereum/assets/14004106/773ae2b6-5d36-48d7-bd37-bc7829317443)

**Comment by maxwolff** [comment]
im down to help out with this.

**Comment by gakonst** [comment]
Go for it Max - and yes it is insane how high quality these geth metrics are

**Comment by maxwolff** [comment]
hey actually a bit confused. DisconnectMetrics gets incremented both for incoming and outgoing dials. "dial metrics" seems to imply it is only relevant for outgoing dials

maybe instead we should keep one set of disconnect metrics on `network/src/manager.rs` for outgoing, one for incoming, and then add the remaining metrics for outgoing dials (rlpx, connection)? otherwise its a bit logically inconsistent. 

eg maybe `pub struct NetworkManager<C> {
..
    metrics: NetworkMetrics,
    incoming_disconnect_metrics: DisconnectMetrics,
    outgoing_disconnect_metrics: DisconnectMetrics,
    dial_metrics: DialMetrics
`


@Rjected

**Comment by Rjected** [comment]
> hey actually a bit confused. DisconnectMetrics gets incremented both for incoming and outgoing dials. "dial metrics" seems to imply it is only relevant for outgoing dials
> 
> maybe instead we should keep one set of disconnect metrics on `network/src/manager.rs` for outgoing, one for incoming, and then add the remaining metrics for outgoing dials (rlpx, connection)? otherwise its a bit logically inconsistent.
> 
> eg maybe
> 
> ```
> pub struct NetworkManager<C> {
> ..
>     metrics: NetworkMetrics,
>     incoming_disconnect_metrics: DisconnectMetrics,
>     outgoing_disconnect_metrics: DisconnectMetrics,
>     dial_metrics: DialMetrics
> ```
> 
> @Rjected

That makes sense. BTW just unassigned, because having people assigned on larger issues like this seems to discourage others from working on them, so I'm taking a more FCFS approach to reviewing PRs

**Comment by emnul** [comment]
I'm working on adding `eth` handshake error metrics. Looks like the changes made in https://github.com/paradigmxyz/reth/pull/3729 were never added to the etc/grafana/dashboards/overview.json file. I can open a separate PR to add those metrics.

**Comment by emhane** [comment]
> I'm working on adding `eth` handshake error metrics. Looks like the changes made in #3729 were never added to the etc/grafana/dashboards/overview.json file. I can open a separate PR to add those metrics.

that is an RLPx metric! it needs to go in the tx pool dashboard **not** the discovery dashboard cc @Rjected

**Comment by emhane** [comment]
all issues here need to take into account https://github.com/paradigmxyz/reth/issues/8150

**Comment by wengDavo** [comment]
Can I jump on this task?

**Comment by emhane** [comment]
sure @wengDavo ! pick any of the checkboxes and complete as its own pr. much easier to review if each checkbox is its own pr.

**Comment by jenpaff** [comment]
might be worth re-prioritising this @Rjected
