### ISSUE TITLE
Tracking: RPC support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#37]
rpc interfaces and types are already added.

### Server

- [x] Implement `Server` instances and all API handlers
- [x] https://github.com/paradigmxyz/reth/issues/1098

### Handlers

- [ ] https://github.com/paradigmxyz/reth/issues/852
- [x] https://github.com/paradigmxyz/reth/issues/604
- [x] https://github.com/paradigmxyz/reth/issues/983
- [x] https://github.com/paradigmxyz/reth/issues/982
- [x] https://github.com/paradigmxyz/reth/issues/981

### Tests

- [ ] Payload testing via rpctestgen

## Current Q

* Database and Pool access: Database abstraction will likely be provided by #29 
* IPC support: not supported by jsonrpsee, could modify IPC support from anvil and use the `Server` impl as well.

**Comment by onbjerg** [comment]
Closing in favor of #1225
