### ISSUE TITLE
Derive networked stage parameters from global memory limit

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#3801]
### Describe the feature

There are certain config parameters that greatly impact memory consumption during networked stages.

For example in the headers downloader:
https://github.com/paradigmxyz/reth/blob/90b6d006d1fc660c4883a4335e42f8e760c4adbe/crates/net/downloaders/src/headers/reverse_headers.rs#L1075-L1103

And the bodies downloader:
https://github.com/paradigmxyz/reth/blob/90b6d006d1fc660c4883a4335e42f8e760c4adbe/crates/net/downloaders/src/bodies/bodies.rs#L505-L527

It would be useful to solve for these config options, given a desired max memory usage. This would not yet cover any stages other than the bodies and headers stages.

To do this, we might first need to bound the `TaskDownloader` channels by _memory_ for the headers and bodies stages.

Headers:
https://github.com/paradigmxyz/reth/blob/90b6d006d1fc660c4883a4335e42f8e760c4adbe/crates/net/downloaders/src/headers/task.rs#L19-L29

Bodies:
https://github.com/paradigmxyz/reth/blob/90b6d006d1fc660c4883a4335e42f8e760c4adbe/crates/net/downloaders/src/bodies/task.rs#L20-L30

```[tasklist]
 - [ ] Introduce global memory upper bound parameter
 - [ ] **Headers**: Bound headers task downloader channel by memory
 - [ ] **Headers** Derive headers configuration with memory upper bound
 - [ ] **Bodies**: Bound bodies task downloader channel by memory
 - [ ] **Bodies** Derive bodies configuration with memory upper bound
 - [ ] Test and validate the upper bound
```

**Comment by ameya-deshmukh** [comment]
@Rjected is this still open to take up?

**Comment by Rjected** [comment]
> @Rjected is this still open to take up?

Yes! If you're working on it, let me know if you have any questions or are stuck!

**Comment by ameya-deshmukh** [comment]
Will do! Thanks a ton

**Comment by ameya-deshmukh** [comment]
@Rjected sorry for not getting back on this, still a medium to low prio issue to work on?

**Comment by Rjected** [comment]
> @Rjected sorry for not getting back on this, still a medium to low prio issue to work on?

np, yeah more or less

**Comment by ameya-deshmukh** [comment]
Thanks :)

**Comment by ameya-deshmukh** [comment]
@mattsse could you assign this to me?

**Comment by mattsse** [comment]
we haven't had issues with this and these can be configured already so I think we can get away without messing with mem size
