### ISSUE TITLE
Tracking: Eth chain tests

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#39]
Run all chain tests from eth/test: https://github.com/ethereum/tests/tree/develop/BlockchainTests
This is one of two ways to check if a client is consistent with ethereum. (Second one is running on mainnet)

# Run test

- [x] Parse json files: https://github.com/foundry-rs/reth/pull/38
- [ ] Transfer json models to `primitives`  and load pre-state to mocked database.
- [ ] Run on stages (maybe modify it if needed) and prepare checks (roots,hashes) that are going to be optional/disabled at first. 

# Mocking

For running tests in stages we wouldn't need inmemory database that would allow us to do that.

- [ ] Define and do cleanup on talked db abstraction.
- [ ] Integrate abstraction inside stages.
- [ ] Mock Database/Trasanction interface with `BTreeMap`.

**Comment by onbjerg** [comment]
I assume this is completed as well, given we run the tests in CI now.
