### ISSUE TITLE
Tracking issue EIP4844 todos

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#3927]
### Describe the feature

```[tasklist]
## TODOS
- [ ] Add `TxEip4844` to the Transaction enum
- [ ] Additional gas/fee functions for blobs
- [ ] Additional optional block data (similar to withdrawals): excessDataGas, dataGasUsed 
- [ ] new genesis config fields: excessDataGas, dataGasUsed 
- [ ] RPC type updates: add optional extra fields, versioned hashes, blob gas fee cap
- [ ] engine API V3 updates: Blobsbundle
- [ ] Additional consensus checks
- [ ] EIP4844 support in txpool
- [ ] forkid/cancun timestamps
- [ ] new transaction errors similar to dynamic fee: "max fee per data gas too low", "max blobs/data reached"
- [ ] network/download changes: custom propagation sqrt peers is too big
```

**Comment by mattsse** [comment]
closed in favor of #2893
