### ISSUE TITLE
Pruning Testing Checklist

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#3958]
### Describe the feature

When https://github.com/paradigmxyz/reth/issues/3428 is done, we need to test different scenarios, e.g.:
1. Archive -> Full Node
2. Full Node from scratch
3. Archive -> Partly pruned node

And, most importantly, we need to check that RPCs, Engine API and other important parts work as expected (with restrictions due to pruning applied).

```[tasklist]
### Sync
- [x] Sync archive node, restart as full with `--full` flag
- [x] Sync full node from scratch
- [x] Sync archive node, restart as pruned with manual pruning configuration in `reth.toml`
```
```[tasklist]
### RPC
- [ ] Endpoints should return meaningful errors when the state at requested block is not available due to pruning: https://github.com/paradigmxyz/reth/pull/4092
```
