### ISSUE TITLE
Tracking: Staged sync

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#40]
## Stage abstraction

This abstraction should be mostly done, pending changes related to how the database abstractions evolve - e.g. instead of taking a raw MDBX transaction, we will likely receive another type in the future.

## Pipeline

- [x] **Better unwind priorities** (@onbjerg): The current unwind priority system is based on Akula's method, but it can and should be simplified to prevent footgunning
- [x] **Error and skip events** (@onbjerg): The pipeline emits events that are currently only used for testing, but may be useful later on for metrics or other things. In some cases `Ran` and `Unwound` events are emitted with "special" values that denote that a stage either failed or was skipped. We should just add events for these cases
- [x] **Commit intervals** (@onbjerg): Currently data is committed to the database every time a stage returns from `Stage::execute`, but realistically this behavior should be tuneable to only commit meaningful progress

## Tooling

- [ ] **Benchmarking helpers**: We want to benchmark stages, so we will probably end up needing some utilities to make that easier
- [ ] **Profiling**: We want insight into what the stages are doing to find paths to optimize. Currently we use `tracing` to mark out spans and emit events - we might be able to leverage this info in conjunction with e.g. `tracing_tracy` to be able to use [Tracy](https://github.com/wolfpld/tracy). However, there may be tools that are better suited for profiling in our case.
- [ ] **Metrics**: While not only a thing for staged sync (we need them in general), tools to expose metrics should be provided as well.

## Stages

Initially we will use the good learnings from Akula, which is based on good learnings from Silkworm and Erigon, and essentially delineate the stages around the same boundaries as they have. As we progress, we might need more stages than listed here (or fewer).

**For the more complex stages I propose we create separate tracking issues that link back to this one.**

- [x] **HeaderDownload** (@rkrasiuk): Downloads headers over P2P
- [ ] **TotalGasIndex**[^1]: Builds an index of `BlockNumber -> TotalGas`. Seems to mostly be used for reporting.
- [x] **BlockHashes**[^1]: Builds an index of `BlockHash -> BlockNumber` from the `BlockNumber -> BlockHash` table built in the `HeaderDownload` stage
- [x] **BodyDownload**: Downloads block bodies and saves a minimal structure containing ommers, the first transaction ID in the block and the number of transactions. Also builds a table of `TxId -> Tx`.
- [x] **TotalTxIndex**[^1]: Builds an index of `BlockNumber -> TotalTx`. Seems to only be used for reporting in the next stage.
- [x] **SenderRecovery**: Recovers sender addresses in each transaction
- [x] **Execution**: Executes blocks
- [x] **HashState**: Hashes accounts and account storage
- [ ] **Interhashes**: Builds trie hashes
- [x] **AccountHistoryIndex**[^1]: Builds indexes related to account histories/changesets
- [x] **StorageHistoryIndex**[^1]: Builds indexes related to storage histories/changesets
- [x] **TxLookup**[^1]: Builds an index of `TxHash -> BlockNumber`, used in the RPC to look up transactions by hash.
- [x] **CallTraceIndex**[^1]: Builds indexes that specify where an account has been the origin or destination of a message
- [ ] **Finish**: Sets the chain tip (used in the RPC to figure out what our latest synced block is)

[^1]: These stages are generally what I would categorize as indexes, which we may be able to generalize somewhat.

**Comment by onbjerg** [comment]
Closing this as it is out of date - the stages have been shuffled around/merged/split etc. We need a few more stages, but those are handled in separate issues.
