### ISSUE TITLE
Tracking: EIP-4844 Networking

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#4052]
This is a tracking issue for what's needed to implement the [Networking](https://eips.ethereum.org/EIPS/eip-4844#networking) section of EIP-4844.

```[tasklist]
### Tasks
- [ ] Add `Encodable` and `Decodable` implementations for `c-kzg` types in `reth-rlp`
- [ ] Include `TxEip4844` in the primitive `Transaction` enum
- [ ] Create blob transaction type with blobs, commitments, proofs
- [ ] Create enum for transaction responses, using the blob transaction
- [ ] Make sure we don't broadcast blob transactions automatically
- [ ] Implement blob validation in transaction pool
```

The network types might end up looking something like this:
```rust
#[derive(Clone, Debug, PartialEq, Eq, RlpEncodableWrapper, RlpDecodableWrapper, Default)]
pub struct PooledTransactions( pub Vec<PooledTransaction> );

pub enum PooledTransaction {
    Normal(TransactionSigned),
    Blob(BlobTransaction)
}

impl Encodable for PooledTransaction {
    // needs custom impl
}

/// A response to [`GetPooledTransactions`] that includes blob data, their commitments, and their
/// corresponding proofs.
// TODO: derive_arbitrary
#[derive(Clone, Debug, PartialEq, Eq, RlpEncodable, RlpDecodable, Default)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub struct BlobTransaction {
    // TODO: include TxEip4844 into TransactionSigned
    /// The transaction payload.
    pub transaction: TransactionSigned,
    /// The transaction's blob data.
    pub blobs: Vec<Blob>,
    /// The transaction's blob commitments.
    pub commitments: Vec<Bytes48>,
    /// The transaction's blob proofs.
    pub proofs: Vec<Bytes48>,
}

impl BlobTransaction {
    // add validation methods that can be used in the pool
}
```

**Comment by 0xJepsen** [comment]
Hows this going? Any chance i could help on this?

**Comment by Rjected** [comment]
> Hows this going? Any chance i could help on this?

Hey! I'm currently working on adding the basic commitment, blob, etc. types from `c_kzg`, along with trait impls like `Encodable` / `Decodable` which along with #4074 should unblock the rest of the tasks. I'll let you know once i'm done with the PR!

**Comment by Hmac512** [comment]
I’d love to help out here as well.

**Comment by 0xJepsen** [comment]
Oh very nice.
