### ISSUE TITLE
Add Ephemery support

### ISSUE THREAD

**Issue by taxmeifyoucan** [paradigmxyz/reth#4340]
### Describe the feature

[Ephemery](https://ephemery.dev) is a new kind of testnet which is intended for short term testing use cases. It automatically resets back to genesis after every given period which enables reclaiming faucet funds, clearing validator set and keeping small state. 

For the best user experience, it would be best to have a CLI flag which automatically connects reth to the latest iteration of Ephemery. Compared to a traditional testnet, adding Ephemery support requires extra feature for generating the current genesis. Current specs for this feature required in clients can be found in [its draft EIP](https://github.com/ethereum/EIPs/blob/04369cb50ee6c1894dec868141e8a32e66dc4f16/EIPS/eip-testnet-draft.md). (specs feedback is welcomed!) 

@T-ess is currently looking into implementing this as part of [her EPF work](https://hackmd.io/@teri-b/HyahzKQhh). I'd suggest @T-ess creates a list of her planned tasks for tracking progress here. 

### Additional context

Ephemery runs since December 2022 but is mostly run by external tooling. This is effort to implement specs also within clients, not only externally. All resources for using the testnet are here https://github.com/ephemery-testnet/ephemery-resources
```[tasklist]
### Tasks
```

**Comment by T-ess** [comment]
This is the rough roadmap for the general Ephemery implementation: 
- [ ] Add Ephemery to the testnet options. Manual network setup would no longer be needed. (In process)
- [ ] Implement the genesis function - automatically create new genesis. (In process)
- [ ] Implement the reset function - automatically remove the old data. (Research phase)

The main goal for now is to have a working genesis implementation in a pair of clients - Lighthouse (CL) and Reth (EL). I created another issue to track the CL progress, for anyone interested: https://github.com/sigp/lighthouse/issues/4664

I will share more detailed information and updates as I progress in the research and implementation.
