### ISSUE TITLE
Tracking: Snapshots

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#4513]
### Describe the feature

Tracking issue for snapshots.

Feature Branch: #5738 

```[tasklist]
## Snapshot Querying
- [ ] #5593 
- [ ] #5654 
- [ ] #5655 
```

```[tasklist]
## Snapshot Writing
- [ ] #5669
- [ ] #5733
- [ ] https://github.com/paradigmxyz/reth/issues/5749
- [ ] https://github.com/paradigmxyz/reth/issues/5752
- [ ] https://github.com/paradigmxyz/reth/issues/5753
- [ ] https://github.com/paradigmxyz/reth/issues/5751
- [ ] https://github.com/paradigmxyz/reth/issues/5750
- [ ] https://github.com/paradigmxyz/reth/issues/5809
```

<details>
  <summary><h3>Previously</h3></summary>
  
```[tasklist]
## Snapshot Format
- [ ] #4512
- [ ] https://github.com/paradigmxyz/reth/pull/4533
- [ ] https://github.com/paradigmxyz/reth/pull/4634
- [ ] https://github.com/paradigmxyz/reth/pull/4642
- [ ] https://github.com/paradigmxyz/reth/pull/4601
- [ ] https://github.com/paradigmxyz/reth/pull/4622
- [ ] https://github.com/paradigmxyz/reth/pull/4682
- [ ] https://github.com/paradigmxyz/reth/pull/4683
- [ ] https://github.com/paradigmxyz/reth/pull/4585
```

```[tasklist]
### Snapshot DB
- [ ] https://github.com/paradigmxyz/reth/issues/4588
- [ ] https://github.com/paradigmxyz/reth/pull/4690
- [ ] https://github.com/paradigmxyz/reth/pull/4721
- [ ] Implement `SnapshotProvider`
- [ ] Check snapshots on pipeline sync
```
  
</details>
