### ISSUE TITLE
Tracking: Ethers -> Alloy transition

### ISSUE THREAD

**Issue by DaniPopes** [paradigmxyz/reth#4715]
# Main transition

```[tasklist]
### Alloy transition
- [ ] #4737
- [ ] #4674
- [ ] #4749
```

# Ethers removal

Note that only `ethers-core` is used in Reth code, while other crates are used only for testing which is fine for now.

## `ethers-core`

```[tasklist]
### `reth-primitives`
- [ ] https://github.com/paradigmxyz/reth/issues/4730
- [ ] https://github.com/paradigmxyz/reth/issues/4789
- [ ] https://github.com/paradigmxyz/reth/issues/4738
- [ ] https://github.com/paradigmxyz/reth/issues/4739
- [ ] https://github.com/paradigmxyz/reth/issues/4740
```

```[tasklist]
### `reth-rpc`
- [ ] https://github.com/paradigmxyz/reth/issues/4742
```

## Rest of Ethers, used in tests

```[tasklist]
### Ethers in tests
- [ ] Migrate network tests to Alloy (blocked on Alloy network implementations)
```

# Further work

```[tasklist]
### Parity removal
- [ ] https://github.com/paradigmxyz/reth/issues/4796
- [ ] https://github.com/paradigmxyz/reth/issues/4797
```

```[tasklist]
### Refactors, upstreaming
- [ ] #4714
- [ ] https://github.com/paradigmxyz/reth/issues/4741
- [ ] https://github.com/paradigmxyz/reth/issues/4743
```

**Comment by gakonst** [comment]
Do we have all the necessary alloy network implementations now? I think so?

**Comment by DaniPopes** [comment]
I've looked at the tests a few days ago. They use an extension to SignerMiddleware with some RPC calls I believe we don't have yet, and the geth wrapper GethInstance to spawn a geth process: https://github.com/paradigmxyz/reth/blob/9aa44093cf2db327220d03386beebd6cc653d87e/crates/net/network/tests/it/clique/geth.rs#L36

This would also unblock https://github.com/paradigmxyz/reth/issues/6006.
