### ISSUE TITLE
Tracking: Hive pyspec failures

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#4812]
We now run the `pyspec` hive test suite, the failures will be tracked here:
```[tasklist]
### `pyspec`
- [ ] https://github.com/paradigmxyz/reth/issues/4811
- [ ] https://github.com/paradigmxyz/reth/issues/4814
- [ ] https://github.com/paradigmxyz/reth/issues/4670
- [ ] https://github.com/paradigmxyz/reth/issues/4815
- [ ] https://github.com/paradigmxyz/reth/issues/4816
```

**Comment by mattsse** [comment]
closing since we're passing all of them now
