### ISSUE TITLE
feat(optimism): Canyon Hardfork Tracker

### ISSUE THREAD

**Issue by clabby** [paradigmxyz/reth#5210]
### Describe the feature

> **Note**
> Will be creating the individual issues this weekend with specs and a high-level overview of what needs to change.

The Canyon hardfork for the OP Stack is currently in-development upstream. This issue will serve as the meta-tracker for all tickets created for implementing support for this next hardfork in `op-reth`.

### Schedule
*Note: The hardfork has not yet been scheduled on any network. This ticket will be updated with the timestamp of each network's transition time as they are scheduled*
| Network | Timestamp  |
| -------- | ------------ |
| Goerli     | `n/a`            |
| Sepolia   | `n/a`            |
| Mainnet  | `n/a`            |

### Tickets

- [ ] Activate Shanghai
- [ ] Add Canyon hardfork types
- [ ] Change EIP-1559 parameters on Canyon transition
- [ ] Fix bug where the `deposit_nonce` is not included in the receipts root hashing in `op-geth` + `op-erigon`.
- [ ] Deploy the `create2Deployer` on the Canyon transition for Base Mainnet only.

### Additional context

**Resources**

* [Reference tracking issue][tracking]. Contains links to reference implementations of the required changes.
* [Reference testing plan][testing]
* [Shanghai Activation Specification][shanghai]

[tracking]: https://github.com/ethereum-optimism/optimism/issues/7452
[testing]: https://github.com/ethereum-optimism/optimism/issues/7731
[shanghai]: https://github.com/ethereum-optimism/optimism/issues/6728

**Comment by clabby** [comment]
Canyon hardfork definition in `revm`: https://github.com/bluealloy/revm/pull/871

**Comment by clabby** [comment]
Closing as done 😄 

reference PRs:
#5551
-> #5542
--> #5527
---> #5526
----> #5504
-----> #5503
------> https://github.com/paradigmxyz/reth/pull/5519
