### ISSUE TITLE
Shorten debug assert output and logging messages

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6415]
### Describe the feature

It's unfortunate if an edge case is caught with a debug assert and unlimited-scroll wasn't enabled for that terminal. ~~Solution is to shorten messages in debug assertions.~~ Nonetheless, the complete output is indispensable for effective debugging.

Same goes for some tracing messages. Additionally some debug messages in scope of `TransactionManager` can be downgraded to trace.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/6863
- [ ] https://github.com/paradigmxyz/reth/pull/6815
- [ ] https://github.com/paradigmxyz/reth/pull/6675
- [ ] https://github.com/paradigmxyz/reth/pull/6988
```
