### ISSUE TITLE
The big `TransactionFetcher` metrics issue

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#6527]
### Describe the feature

Collection of metrics issues for `TransactionFetcher`

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/6526
- [ ] https://github.com/paradigmxyz/reth/issues/6524
- [ ] https://github.com/paradigmxyz/reth/issues/6529
- [ ] https://github.com/paradigmxyz/reth/issues/6530
```

**Comment by AbnerZheng** [comment]
Yes! Maybe I can address more metrics issues if you like :D
