### ISSUE TITLE
Tracking: DB

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#66]
TODO:
- [x] Abstraction layer
- [x] Fuzz test (`proptest`) ser/de
- [x] Benchmarks speed vs size - types and codecs
- [x] conditional dependencies for `db/codecs` https://github.com/foundry-rs/reth/pull/51

Continuous work:
- [ ] More tables
- [ ] Add proper codec annotations to tables

---

Codec Abstraction: https://github.com/foundry-rs/reth/pull/51
DataApi [discussion]:  https://github.com/foundry-rs/reth/pull/29
MDBX table implementation: https://github.com/foundry-rs/reth/pull/15

**Comment by gakonst** [comment]
Closing, I consider DB features complete and anything we need to implement further is optimizations.
