### ISSUE TITLE
Performance metrics for different network component futures

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#6686]
### Describe the feature

We should add metrics for how long different sections of the `TransactionsManager` and `NetworkManager` futures take. For example, the transactions manager future:
https://github.com/paradigmxyz/reth/blob/cb61334b2cd04e9f7e97724aa9faca00ac0b46ba/crates/net/network/src/transactions/mod.rs#L1084-L1201

This has a few sections:
* poll and process a network event
* call `on_fetch_pending_hashes`
* poll and process a command
* poll and process fetch events
* poll and process imports
* drain pending txs and process

We should determine _accumulated_ metrics for these steps, meaning, it should count time taken over multiple `loop`s in the transactions manager, since the future is budgeted. This way we can check how long processing imports takes in a single `poll` call to the transactions manager.

This would allow us to measure over time, which steps of the future become bottlenecks under load, as well as how long, in total, the total poll call typically takes.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/6737
- [ ] https://github.com/paradigmxyz/reth/issues/6745
- [ ] https://github.com/paradigmxyz/reth/pull/6814
- [ ] https://github.com/paradigmxyz/reth/pull/6892
```

**Comment by emhane** [comment]
related https://github.com/paradigmxyz/reth/issues/6643
