### ISSUE TITLE
Implement Admin namespace RPC handler

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#672]
### Describe the feature

ref #549

Start scaffolding `admin` namespace RPC handler impl.

API trait first added here: #569

This will look similar to the `NetApi`:

https://github.com/paradigmxyz/reth/blob/20847845e2d7518515ba514815b1987de8f95e27/crates/net/rpc/src/net/mod.rs#L7-L12

# TODO

- [ ] add `AdminApi` type which should also take `NetworkHandle`
- [ ] implement `AdminApiServer` trait on it
- [ ] implement admin functions via `NetworkHandle`

**Comment by leruaa** [comment]
I would like to take this on

**Comment by mattsse** [comment]
awesome!

**Comment by leruaa** [comment]
@mattsse Not sure to understand why `AdminApiServer` `add_peer()` and `remove_peer()` need to be async?

We just need to call `NetworkHandle` `add_peer()` and `disconnect_peer_with_reason()`, no?

**Comment by mattsse** [comment]
they don't, so feel free to change that in the trait

**Comment by leruaa** [comment]
@mattsse I'm not sure `add_trusted_peer` and `remove_trusted_peer` should do, as trusted nodes are stored on `PeersConfig` and seems to be used only when Reth starts. Am I missing something?

Also, it seems `connect_trusted_nodes_only` is never used.

**Comment by mattsse** [comment]
the `connect_trusted_nodes_only` setting is enforced here

https://github.com/paradigmxyz/reth/blob/13441ff299b4766959b5439235dfed2071059c54/crates/net/network/src/peers/manager.rs#L469

> and seems to be used only when Reth starts. Am I missing something?

right, will create a separate issue for adding commands, similar to `add_peer`
