### ISSUE TITLE
Tracking: Execution/Validation of blocks

### ISSUE THREAD

**Issue by rakita** [paradigmxyz/reth#72]
Cover all needed validation and building for Ethereum block/header inside one library so it can be reused if needed. It will contain the main execution with EVM and all checks required for validating and creating blocks.

Some checks can differ depending on the consensus in place.

Common tasks:
- [x] Implement rlp for all primitive types.

# Validator

Have utilities for stages to check parts of header/block/transactions fields. Those functions need to be aligned with the need (performance) of every stage. Some of those checks can be placed inside `reth-primitives`.

* [x]  https://github.com/foundry-rs/reth/pull/152
* [x] Transaction signature recovery: https://github.com/foundry-rs/reth/pull/179
* [ ] Transaction verification 

# Builder

Have the ability with a list of transactions to create state change and all needed fields for the header.
TODO tasks

# Transaction execution

* [x] Storage provider: https://github.com/foundry-rs/reth/pull/172
* [x] Transaction execution with storage provider. https://github.com/foundry-rs/reth/pull/238 

Have the ability to execute:
* Past transaction's
* given transaction on:
  * Latest state
  * State from past.

**Comment by onbjerg** [comment]
Is this done? @rakita 

If not, what's missing?

**Comment by rakita** [comment]
The validator is done, and part of the transaction execution. but maybe it will be more efficient to split it into more meaningful issues.

**Comment by onbjerg** [comment]
That would be great.

**Comment by rakita** [comment]
Created tasks:
https://github.com/paradigmxyz/reth/issues/1012
https://github.com/paradigmxyz/reth/issues/1009
https://github.com/paradigmxyz/reth/issues/1013
