### ISSUE TITLE
Tracking: Execution Extensions

### ISSUE THREAD

**Issue by shekhirin** [paradigmxyz/reth#7549]
https://github.com/paradigmxyz/reth/blob/283b56c1b9931412723d8cf628fd075bb854f73b/crates/node-builder/src/exex.rs#L3-L7

```[tasklist] 
# Implementation
- [ ] #7235
- [ ] #7506
- [ ] #7340
- [ ] #7547
- [ ] #7546
- [ ] #7550
- [ ] https://github.com/paradigmxyz/reth/issues/7570
- [ ] https://github.com/paradigmxyz/reth/issues/7572
- [ ] https://github.com/paradigmxyz/reth/issues/7630
- [ ] https://github.com/paradigmxyz/reth/issues/7629
- [ ] https://github.com/paradigmxyz/reth/issues/10489
```

```[tasklist]
# Examples
- [ ] https://github.com/paradigmxyz/reth/issues/7557
- [ ] #7556
- [ ] https://github.com/paradigmxyz/reth/issues/7558
- [ ] https://github.com/paradigmxyz/reth/issues/7571
```
