### ISSUE TITLE
reth cli abstraction

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#7576]
### Describe the feature

Currently all version related stuff is fixed via `node-core/build`.

we want to support custom cli settings, which is also required to make the binary work for both op and reth or building you own while reusing all existing argument types

Supersedes #6218

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/issues/9083
- [ ] https://github.com/paradigmxyz/reth/issues/9095
- [ ] https://github.com/paradigmxyz/reth/issues/9100
- [ ] https://github.com/paradigmxyz/reth/pull/9098
- [ ] https://github.com/paradigmxyz/reth/issues/9084
- [ ] https://github.com/paradigmxyz/reth/issues/8623
- [ ] https://github.com/paradigmxyz/reth/issues/9139
- [ ] https://github.com/paradigmxyz/reth/issues/9220
- [ ] https://github.com/paradigmxyz/reth/issues/9260
- [ ] https://github.com/paradigmxyz/reth/issues/9266
- [ ] https://github.com/paradigmxyz/reth/issues/9267
- [ ] https://github.com/paradigmxyz/reth/issues/9407
- [ ] https://github.com/paradigmxyz/reth/issues/9408
- [ ] https://github.com/paradigmxyz/reth/issues/9409
- [ ] https://github.com/paradigmxyz/reth/issues/9450
```
