### ISSUE TITLE
Remove optimism feature

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#7649]
### Describe the feature

Gathers issues to re-design code to remove optimism feature. Features are convenient for building fast, but in the long run make the code harder to maintain.

A generalisation of the codebase in terms of EVM rollup injectable types, is required to extract OP as a library as, opposed to having OP as a feature.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/13441
- [ ] https://github.com/paradigmxyz/reth/issues/13440
- [ ] https://github.com/paradigmxyz/reth/issues/11116
- [ ] https://github.com/paradigmxyz/reth/issues/6906
- [ ] https://github.com/paradigmxyz/reth/issues/7648
- [ ] https://github.com/paradigmxyz/reth/pull/8487
- [ ] https://github.com/paradigmxyz/reth/issues/8499
- [ ] https://github.com/paradigmxyz/reth/pull/7740
- [ ] https://github.com/paradigmxyz/reth/pull/6902
- [ ] https://github.com/paradigmxyz/reth/issues/8988
- [ ] https://github.com/paradigmxyz/reth/issues/8904
- [ ] https://github.com/paradigmxyz/reth/issues/10515
- [ ] https://github.com/paradigmxyz/reth/issues/11109
- [ ] https://github.com/paradigmxyz/reth/issues/11111
- [ ] https://github.com/paradigmxyz/reth/issues/11172
- [ ] https://github.com/paradigmxyz/reth/issues/11253
- [ ] https://github.com/paradigmxyz/reth/issues/11434
- [ ] https://github.com/paradigmxyz/reth/issues/11530
- [ ] https://github.com/paradigmxyz/reth/issues/11533
- [ ] https://github.com/paradigmxyz/reth/issues/11531
- [ ] https://github.com/paradigmxyz/reth/issues/11534
- [ ] https://github.com/paradigmxyz/reth/issues/11536
- [ ] https://github.com/paradigmxyz/reth/issues/11566
- [ ] https://github.com/paradigmxyz/reth/issues/11572
- [ ] https://github.com/paradigmxyz/reth/issues/11108
- [ ] https://github.com/paradigmxyz/reth/issues/11792
- [ ] https://github.com/paradigmxyz/reth/issues/12169
- [ ] https://github.com/paradigmxyz/reth/issues/12333
- [ ] https://github.com/paradigmxyz/reth/issues/12184
- [ ] https://github.com/paradigmxyz/reth/issues/11575
- [ ] https://github.com/paradigmxyz/reth/issues/12473
- [ ] https://github.com/paradigmxyz/reth/issues/12475
- [ ] https://github.com/paradigmxyz/reth/issues/12516
- [ ] https://github.com/paradigmxyz/reth/issues/12587
- [ ] https://github.com/paradigmxyz/reth/issues/12588
```

**Comment by supernovahs** [comment]
I can take this?

**Comment by onbjerg** [comment]
@supernovahs This is a longer term project and requires re-architecting some parts of the node and node dependencies, which requires high context. We are not currently looking to outsource this, but thank you for your interest :)

**Comment by mattsse** [comment]
I'm marking this as completed because we no longer have feature gated types

and the existing crate level op features should go away naturally with revm upgrade
