### ISSUE TITLE
Tracking: Prague / Electra EIPs

### ISSUE THREAD

**Issue by gakonst** [paradigmxyz/reth#7691]
```[tasklist]
# EIPs
- [x] [EIP-2537: Precompile for BLS12-381 curve operations](https://eips.ethereum.org/EIPS/eip-2537)
- [ ] [EIP-7002: Execution layer triggerable exits](https://eips.ethereum.org/EIPS/eip-7002#execution-layer)
- [ ] [EIP-6110: Supply validator deposits on chain](https://eips.ethereum.org/EIPS/eip-6110#execution-layer)
- [ ]  [EIP-2935 Save historical block hashes in state](https://eips.ethereum.org/EIPS/eip-2935), Issue, PR
- [x] [EIP-3074: AUTH/AUTHCALL](https://eips.ethereum.org/EIPS/eip-3074), Issue, PR
```

# Additional Notes

- **EIP-7002** and **EIP-2935** fit well within the proposed abstraction for Begin/EndBlock for CORE.
- **EIP-6110** may require consideration of Alloy types to address potential divergence between L1 and L2 layers.

**Comment by gakonst** [comment]
dup #7363
