### ISSUE TITLE
Add actual PoolTransaction struct

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#786]
### Describe the feature

The txpool relies on:

https://github.com/paradigmxyz/reth/blob/a51fa4fd6399cf613cd71586229beca0a62c50b5/crates/transaction-pool/src/traits.rs#L238

which provides all the information required by the pool to do validation, ordering etc..

The recovered tx type (tx object + recovered sender) is

https://github.com/paradigmxyz/reth/blob/258431aac8c5ee2eb931c4ee566235e6982d4acb/crates/primitives/src/transaction/mod.rs#L762-L765

some parts of the txpool require info derived from static fields, for example cost, effective gas price (EIP1559) but most importantly the hash, which is used a lot.

To make this efficient, we need a new type that has these derived values as fields so they only need to be calculated once.

For example foundry's pool type is:

https://github.com/foundry-rs/foundry/blob/a44aa13cfc23491ba32aaedc093e9488c1a6db43/anvil/src/eth/pool/transactions.rs#L79-L90

which is basically:
tx + sender + hash + additional stuff used by the pool

The new tx type should look similar.

## TODO

- [ ] introduce main PoolTransaction struct (naming tbd)
- [ ] impl `PoolTransaction` trait
- [ ] impl conversion traits `FromRecoveredTransaction` `IntoRecoveredTransaction`

**Comment by literallymarvellous** [comment]
Hi, would like to take this. 

I've started on an implementation. I have the PoolTransaction struct is in the same file as the PoolTransaction trait and the struct consists of all the PoolTransaction trait functions as fields and a TransactionSignedEcRecovered transaction field, don't know if that's accurate.

Also how do I go about accessing the basefee value for the transaction pool.

**Comment by mattsse** [comment]
awesome sounds good, please open a PR and we can go over it!
