### ISSUE TITLE
DB writes, bottleneck during sync

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8303]
### Describe the feature

Canonicalization on FCU competes over rw access to db, with deleting entires on pruning. This leads to issues syncing.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/7500
- [ ] https://github.com/paradigmxyz/reth/issues/7477
- [ ] https://github.com/paradigmxyz/reth/issues/8203
- [ ] https://github.com/paradigmxyz/reth/issues/7343
- [ ] https://github.com/paradigmxyz/reth/issues/7505
- [ ] https://github.com/paradigmxyz/reth/pull/6792
- [ ] https://github.com/paradigmxyz/reth/issues/6796
- [ ] https://github.com/paradigmxyz/reth/issues/7435
- [ ] https://github.com/paradigmxyz/reth/issues/6770
- [ ] https://github.com/paradigmxyz/reth/issues/8957
```

**Comment by emhane** [comment]
is this issue irrelevant with new db design @Rjected @fgimenez  ?

**Comment by fgimenez** [comment]
> is this issue irrelevant with new db design [@Rjected](https://github.com/Rjected) [@fgimenez](https://github.com/fgimenez) ?

yes, this should be fixed with the new design
