### ISSUE TITLE
Failing hive engine-api tests

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8305]
#### Inconsistent Head in ForkchoiceState

- [ ]  test=60 name="Inconsistent Head in ForkchoiceState (Cancun) (reth)"

#### Invalid Missing Ancestor

- [ ]  test=135 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=False, Invalid P9 (Cancun) (reth)"
- [ ]  test=136 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=False, Invalid P9 (Cancun) (reth)"
- [ ]  test=137 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=True, CanonicalReOrg=True, Invalid P9 (Cancun) (reth)"
- [ ]  test=138 name="Invalid Missing Ancestor Syncing ReOrg, StateRoot, EmptyTxs=False, CanonicalReOrg=True, Invalid P9 (Cancun) (reth)"
- [ ]  test=141 name="Invalid Missing Ancestor Syncing ReOrg, GasLimit, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (reth)"
- [ ]  test=145 name="Invalid Missing Ancestor Syncing ReOrg, Timestamp, EmptyTxs=False, CanonicalReOrg=False, Invalid P8 (Cancun) (reth)"

#### Invalid NewPayload

- [ ]  test=84 name="Invalid NewPayload, StateRoot, Syncing=True, EmptyTxs=True, DynFeeTxs=False (Cancun) (reth)"
- [ ]  test=85 name="Invalid NewPayload, StateRoot, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"
- [ ]  test=97 name="Invalid NewPayload, PrevRandao, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/6217
- [ ] https://github.com/paradigmxyz/reth/issues/7146
```

**Comment by fgimenez** [comment]
for regular engine all the test are fixed, and for experimental engine the rest will be fixed with #11265
