### ISSUE TITLE
Failing hive engine cancun tests

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8306]
#### Blob tx ordering

- [ ]  test=7 name=“Blob Transaction Ordering, Multiple Clients (Cancun) (reth)" https://github.com/paradigmxyz/reth/issues/7144

#### Invalid NewPayload

- [x]  test=208 name="Invalid NewPayload, ParentBeaconBlockRoot, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"
- [ ]  test=199 name="Invalid PayloadAttributes, Missing BeaconRoot, Syncing=True (Cancun) (reth)"
- [x]  test=210 name="Invalid NewPayload, BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"
- [x]  test=212 name="Invalid NewPayload, Blob Count on BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"
- [ ]  test=214 name="Invalid NewPayload, ExcessBlobGas, Syncing=True, EmptyTxs=False, DynFeeTxs=False (Cancun) (reth)"

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/7144
```

**Comment by Rjected** [comment]
Did some investigation on the `Invalid NewPayload, BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False` test.

For the `Invalid NewPayload, BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False` test we have the following log:
```
>> (203fb4e1) {"jsonrpc":"2.0","id":18,"method":"engine_newPayloadV3","params":[{"parentHash":"0x051b7e243652032aadc3026daa1757588b2bfece483bc469e828ba78ce6d08d8","feeRecipient":"0x0000000000000000000000000000000000000000","stateRoot":"0x00205af9fe548ff77b90484a2c189f7dcb9827a2d14872269a47e173d3ae2d57","receiptsRoot":"0xe610d851a7fc9b06c4eb4472911f6434c4c5f5877400edff4f1e0bec451e24a6","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","prevRandao":"0x4b7b9379f7e04af87a2e52a6b3810e0ad69d5dcae2a36a0663df9e055163a868","blockNumber":"0x7","gasLimit":"0x2fefd8","gasUsed":"0xa860","timestamp":"0x123b","extraData":"0x726574682f76312e302e362f6c696e7578","baseFeePerGas":"0x17f663e8","blockHash":"0xb9b507c2c2df38d599c0ecbd0f922b838083e9dff72b53f197c396a5c9bad156","transactions":["0x03f901390780843b9aca008506fc23ac00830124f89400000000000000000000000000000000000003160180c0843b9aca00f8c6a0010657f37554c781402a22917dee2f75def7ab966d7b770905398eba3c444014a001a25482abd730f338318967ad234e93023c62f97bed67fcee9f2c714824bf6fa001882e0bf2b807e8c5e248bfcd51254530ecf28ba0c38f9e25cc5cd6b73bb64ba001c714aabad7d830065b8e8e288de70d95d3de7d60be99004088253e2f00bd47a001b2eed9641206c26dd711f9375bd1a0a0469e9b97256d94126fd916e4f2053da00131fc35acbbd321d0e71ec98451b8f1221df978a1254951d97d98c143d2081401a06d5c967af1660ab389b434d648c51f62fc66be02ef9bd77afdc185d638f0d08aa0378260f6fd23222ca5a01b8161cb1f96a2aba0516c5d8e6ba09cd9586c02d64b"],"withdrawals":[{"index":"0x3d","validatorIndex":"0x0","address":"0x0000000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3e","validatorIndex":"0x1","address":"0x0100000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3f","validatorIndex":"0x2","address":"0x0200000000000000000000000000000000000000","amount":"0x64"},{"index":"0x40","validatorIndex":"0x3","address":"0x0300000000000000000000000000000000000000","amount":"0x64"},{"index":"0x41","validatorIndex":"0x4","address":"0x0400000000000000000000000000000000000000","amount":"0x64"},{"index":"0x42","validatorIndex":"0x5","address":"0x0500000000000000000000000000000000000000","amount":"0x64"},{"index":"0x43","validatorIndex":"0x6","address":"0x0600000000000000000000000000000000000000","amount":"0x64"},{"index":"0x44","validatorIndex":"0x7","address":"0x0700000000000000000000000000000000000000","amount":"0x64"},{"index":"0x45","validatorIndex":"0x8","address":"0x0800000000000000000000000000000000000000","amount":"0x64"},{"index":"0x46","validatorIndex":"0x9","address":"0x0900000000000000000000000000000000000000","amount":"0x64"}],"blobGasUsed":"0xc0001","excessBlobGas":"0x240000"},["0x010657f37554c781402a22917dee2f75def7ab966d7b770905398eba3c444014","0x01a25482abd730f338318967ad234e93023c62f97bed67fcee9f2c714824bf6f","0x01882e0bf2b807e8c5e248bfcd51254530ecf28ba0c38f9e25cc5cd6b73bb64b","0x01c714aabad7d830065b8e8e288de70d95d3de7d60be99004088253e2f00bd47","0x01b2eed9641206c26dd711f9375bd1a0a0469e9b97256d94126fd916e4f2053d","0x0131fc35acbbd321d0e71ec98451b8f1221df978a1254951d97d98c143d20814"],"0x0f1692d95c1d1ab6eaf88762481835070098bd5b3f108e6d479c7f3e9c3e8592"]}
<< (203fb4e1) {"jsonrpc":"2.0","id":18,"result":{"status":"INVALID","latestValidHash":null,"validationError":"blob gas used 786433 exceeds maximum allowance 786432"}}
>> (203fb4e1) {"jsonrpc":"2.0","id":19,"method":"engine_forkchoiceUpdatedV3","params":[{"headBlockHash":"0xb9b507c2c2df38d599c0ecbd0f922b838083e9dff72b53f197c396a5c9bad156","safeBlockHash":"0xb9b507c2c2df38d599c0ecbd0f922b838083e9dff72b53f197c396a5c9bad156","finalizedBlockHash":"0xb9b507c2c2df38d599c0ecbd0f922b838083e9dff72b53f197c396a5c9bad156"},{"timestamp":"0x123c","prevRandao":"0x0000000000000000000000000000000000000000000000000000000000000000","suggestedFeeRecipient":"0x0000000000000000000000000000000000000000","withdrawals":[{"index":"0x3d","validatorIndex":"0x0","address":"0x0000000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3e","validatorIndex":"0x1","address":"0x0100000000000000000000000000000000000000","amount":"0x64"},{"index":"0x3f","validatorIndex":"0x2","address":"0x0200000000000000000000000000000000000000","amount":"0x64"},{"index":"0x40","validatorIndex":"0x3","address":"0x0300000000000000000000000000000000000000","amount":"0x64"},{"index":"0x41","validatorIndex":"0x4","address":"0x0400000000000000000000000000000000000000","amount":"0x64"},{"index":"0x42","validatorIndex":"0x5","address":"0x0500000000000000000000000000000000000000","amount":"0x64"},{"index":"0x43","validatorIndex":"0x6","address":"0x0600000000000000000000000000000000000000","amount":"0x64"},{"index":"0x44","validatorIndex":"0x7","address":"0x0700000000000000000000000000000000000000","amount":"0x64"},{"index":"0x45","validatorIndex":"0x8","address":"0x0800000000000000000000000000000000000000","amount":"0x64"},{"index":"0x46","validatorIndex":"0x9","address":"0x0900000000000000000000000000000000000000","amount":"0x64"}],"parentBeaconBlockRoot":"0x0f1692d95c1d1ab6eaf88762481835070098bd5b3f108e6d479c7f3e9c3e8592"}]}
<< (203fb4e1) {"jsonrpc":"2.0","id":19,"result":{"payloadStatus":{"status":"INVALID","latestValidHash":"0x0000000000000000000000000000000000000000000000000000000000000000","validationError":"links to previously rejected block"},"payloadId":null}}
DEBUG (Invalid NewPayload, BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False): Failed `Expect*` routine called from: file=/source/suites/engine/invalid_payload.go, line=204
```

This is the corresponding [code](https://github.com/ethereum/hive/blob/91829ccfb2c55687d3f8b543203be4379cdde1be/simulators/ethereum/engine/suites/engine/invalid_payload.go#L204) from the test:
```go
			// Depending on the field we modified, we expect a different status
			r := t.TestEngine.TestEngineNewPayload(alteredPayload)
			if tc.Syncing || tc.InvalidField == helper.InvalidParentHash {
// ... more comments
					r.ExpectStatusEither(test.Invalid, test.Accepted, test.Syncing)
			} else {
				r.ExpectStatus(test.Invalid)
				if !(nilLatestValidHash && r.Status.LatestValidHash == nil) {
					r.ExpectLatestValidHash(&alteredPayload.ParentHash)
				}
			}
			s := t.TestEngine.TestEngineForkchoiceUpdated(&fcState, &payloadAttrbutes, alteredPayload.Timestamp)
			if !tc.Syncing {
				s.ExpectAnyPayloadStatus(test.Syncing, test.Accepted, test.Invalid)
			} else {
				s.ExpectPayloadStatus(test.Syncing) // <-- THIS is where we fail
// rest of the code...
			}
```

I am a bit confused why the test expects `SYNCING` here, unless it has something to do with the payload attributes.
Clearly if we were able to detect that the payload `0xb9b507c2c2df38d599c0ecbd0f922b838083e9dff72b53f197c396a5c9bad156` is `INVALID`, then we know that any FCU with that block is also `INVALID`.

Test can be run with:
```
./hive --sim ethereum/engine --client reth --sim.limit "engine-cancun/Invalid NewPayload, BlobGasUsed, Syncing=True, EmptyTxs=False, DynFeeTxs=False"
```

**Comment by fgimenez** [comment]
yep, and if we don't add the header to the invalid headers list in `on_new_head`, the test passes... 

the really weird thing for me is that this test passes for the rest of EL clients, and looks like we are doing the right thing according to the spec, wdyt?

**Comment by emhane** [comment]
would be great if you open a hive issue in that case and mark this issue as blocked, with link to hive issue @fgimenez

**Comment by fgimenez** [comment]
> would be great if you open a hive issue in that case and mark this issue as blocked, with link to hive issue @fgimenez

was already fixed here https://github.com/ethereum/hive/pull/1159 so we are passing these tests now, I'll propose a PR to remove them from expected failures

**Comment by fgimenez** [comment]
> is this issue closed now [@fgimenez](https://github.com/fgimenez) ?

no, the pending tests are still expected failures https://github.com/paradigmxyz/reth/blob/main/.github/assets/hive/expected_failures.yaml#L24-L42

**Comment by jenpaff** [comment]
tracked in expected failures https://github.com/paradigmxyz/reth/blob/eaa45abb989646fad41b38a161e2f948ec36df7a/.github/assets/hive/expected_failures.yaml#L46
