### ISSUE TITLE
Tracking: Hive support

### ISSUE THREAD

**Issue by onbjerg** [paradigmxyz/reth#851]
### Describe the feature

This is a tracking issue to add reth to [ethereum/hive](https://github.com/ethereum/hive).

A draft PR in the hive repository is open here: https://github.com/ethereum/hive/pull/671

This tracking issue is currently non-exhaustive.

### devp2p

```[tasklist]
#### devp2p/discv4

- [x] #852
- [x] #850 
- [x] #849 
- [x] https://github.com/paradigmxyz/reth/issues/854
- [x] https://github.com/paradigmxyz/reth/issues/858
- [ ] https://github.com/paradigmxyz/reth/issues/1262
```

```[tasklist]
#### devp2p/eth

- [x] #879
- [x] #878
- [ ] https://github.com/paradigmxyz/reth/issues/1262
```

### eth2/testnet

TBD

```[tasklist]
### ethereum/consensus

Essentially the same as Ethereum state tests which we run [here](https://github.com/paradigmxyz/reth/actions/runs/3910595705/jobs/6682974831)

- [x] #879
- [x] #878
- [ ] #1225
- [ ] https://github.com/paradigmxyz/reth/issues/1262
```

### ethereum/engine

TBD

```[tasklist]
### ethereum/rpc-compat

- [x] #879
- [x] #878
- [ ] #1225
- [ ] https://github.com/paradigmxyz/reth/issues/1262
```

```[tasklist]
### ethereum/rpc

- [x] #879
- [x] #878
- [ ] #1225
- [x] #36
- [ ] Block building
- [ ] https://github.com/paradigmxyz/reth/issues/1262
```

```[tasklist]
### ethereum/sync

- [x] #879
- [x] #878
- [ ] #1225
- [ ] https://github.com/paradigmxyz/reth/issues/1262
```

```[tasklist]
## Meta

- [ ] #855
- [ ] Build and publish Docker images (on push tagged with branch name on `main`, tagged with version on release)
```

# How to run the tests

1. Build the Docker image in *this* repository: `docker build . -t paradigmxyz/reth:main`
2. Clone https://github.com/paradigmxyz/hive
3. Build hive: `go build .`
4. Run Hive, specifying `reth` as the client e.g.: `./hive --sim devp2p --sim.limit discv4 --client reth --docker.output`. See [this document](https://github.com/ethereum/hive/blob/master/docs/commandline.md) for usage information.
5. Logs and results are placed in the `workspace` directory relative to your current working directory. They can be viewed with `hiveview` which can be built with `go build -o hiveview ./cmd/hiveview` and run with `./hiveview -serve`
