### ISSUE TITLE
Types abstraction

### ISSUE THREAD

**Issue by joshieDo** [paradigmxyz/reth#8721]
### Describe the feature

Having a minimal representation of certain types allows for more modularity. 

Similar to https://github.com/alloy-rs/alloy/blob/5814686ef5f4123d35630611045a5c8b5a41a6c5/crates/consensus/src/transaction/mod.rs#L38

```[tasklist]
- [ ] `reth-primitives-traits` #8722
- [ ] `Account` #8722
- [ ] `Receipt`
- [ ] `Block`
- [ ] https://github.com/paradigmxyz/reth/issues/8748
- [ ] https://github.com/paradigmxyz/reth/issues/8825
- [ ] https://github.com/paradigmxyz/reth/issues/9484
```

alloy block abstraction https://github.com/alloy-rs/alloy/pull/1106
