### ISSUE TITLE
Tracking: Engine revamp

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8742]
### Describe the feature

The current engine <-> tree design has several drawbacks

* sequential processing

* Tree Read lock that interferes with rpc (pending block access)

* very complex request processing that requires multiple tree access roundtrips

* This must be redesigned entirely

This should allow us to support other interfaces like ABCI,Arbitrum or others via the Node Builder

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/issues/8744
- [ ] https://github.com/paradigmxyz/reth/issues/8745
- [ ] https://github.com/paradigmxyz/reth/issues/8746
- [ ] https://github.com/paradigmxyz/reth/issues/8747
- [ ] https://github.com/paradigmxyz/reth/issues/9559
- [ ] https://github.com/paradigmxyz/reth/issues/9008
- [ ] https://github.com/paradigmxyz/reth/issues/9009
- [ ] https://github.com/paradigmxyz/reth/issues/9011
- [ ] https://github.com/paradigmxyz/reth/issues/9012
- [ ] https://github.com/paradigmxyz/reth/pull/8559
- [ ] https://github.com/paradigmxyz/reth/issues/9151
- [ ] https://github.com/paradigmxyz/reth/issues/9576
- [ ] https://github.com/paradigmxyz/reth/issues/9577
- [ ] https://github.com/paradigmxyz/reth/issues/9582
- [ ] https://github.com/paradigmxyz/reth/issues/9607
- [ ] https://github.com/paradigmxyz/reth/issues/9614
- [ ] https://github.com/paradigmxyz/reth/issues/9615
- [ ] https://github.com/paradigmxyz/reth/issues/9617
- [ ] https://github.com/paradigmxyz/reth/issues/9638
- [ ] https://github.com/paradigmxyz/reth/issues/9644
- [ ] https://github.com/paradigmxyz/reth/issues/9671
- [ ] https://github.com/paradigmxyz/reth/issues/9672
- [ ] https://github.com/paradigmxyz/reth/issues/9673
- [ ] https://github.com/paradigmxyz/reth/issues/9685
- [ ] https://github.com/paradigmxyz/reth/issues/9688
- [ ] https://github.com/paradigmxyz/reth/issues/9689
- [ ] https://github.com/paradigmxyz/reth/issues/9694
- [ ] https://github.com/paradigmxyz/reth/issues/9696
- [ ] https://github.com/paradigmxyz/reth/issues/9700
- [ ] https://github.com/paradigmxyz/reth/issues/9705
- [ ] https://github.com/paradigmxyz/reth/issues/9731
- [ ] https://github.com/paradigmxyz/reth/issues/9749
- [ ] https://github.com/paradigmxyz/reth/issues/9750
- [ ] https://github.com/paradigmxyz/reth/issues/9752
- [ ] https://github.com/paradigmxyz/reth/issues/9753
- [ ] https://github.com/paradigmxyz/reth/issues/9760
- [ ] https://github.com/paradigmxyz/reth/issues/9777
- [ ] https://github.com/paradigmxyz/reth/issues/9778
- [ ] https://github.com/paradigmxyz/reth/issues/9793
- [ ] https://github.com/paradigmxyz/reth/issues/9794
- [ ] https://github.com/paradigmxyz/reth/issues/9806
- [ ] https://github.com/paradigmxyz/reth/issues/9807
- [ ] https://github.com/paradigmxyz/reth/issues/9812
- [ ] https://github.com/paradigmxyz/reth/issues/9815
- [ ] https://github.com/paradigmxyz/reth/issues/9821
- [ ] https://github.com/paradigmxyz/reth/issues/9825
- [ ] https://github.com/paradigmxyz/reth/issues/9828
- [ ] https://github.com/paradigmxyz/reth/issues/9829
- [ ] https://github.com/paradigmxyz/reth/issues/9849
- [ ] https://github.com/paradigmxyz/reth/issues/9893
- [ ] https://github.com/paradigmxyz/reth/issues/9897
- [ ] https://github.com/paradigmxyz/reth/issues/9899
- [ ] https://github.com/paradigmxyz/reth/issues/9909
- [ ] https://github.com/paradigmxyz/reth/issues/9923
- [ ] https://github.com/paradigmxyz/reth/issues/9924
- [ ] https://github.com/paradigmxyz/reth/issues/9926
- [ ] https://github.com/paradigmxyz/reth/issues/9935
- [ ] https://github.com/paradigmxyz/reth/issues/9957
- [ ] https://github.com/paradigmxyz/reth/issues/9958
- [ ] https://github.com/paradigmxyz/reth/issues/9978
- [ ] https://github.com/paradigmxyz/reth/issues/9535
- [ ] https://github.com/paradigmxyz/reth/issues/10007
- [ ] https://github.com/paradigmxyz/reth/issues/10009
- [ ] https://github.com/paradigmxyz/reth/issues/10015
- [ ] https://github.com/paradigmxyz/reth/issues/10017
- [ ] https://github.com/paradigmxyz/reth/issues/10018
- [ ] https://github.com/paradigmxyz/reth/issues/10037
- [ ] https://github.com/paradigmxyz/reth/issues/10038
- [ ] https://github.com/paradigmxyz/reth/issues/10096
- [ ] https://github.com/paradigmxyz/reth/issues/10097
- [ ] https://github.com/paradigmxyz/reth/issues/10098
- [ ] https://github.com/paradigmxyz/reth/issues/10104
- [ ] https://github.com/paradigmxyz/reth/issues/10115
- [ ] https://github.com/paradigmxyz/reth/issues/10123
- [ ] https://github.com/paradigmxyz/reth/issues/10124
- [ ] https://github.com/paradigmxyz/reth/issues/10145
- [ ] https://github.com/paradigmxyz/reth/issues/10157
- [ ] https://github.com/paradigmxyz/reth/issues/10159
- [ ] https://github.com/paradigmxyz/reth/issues/10160
- [ ] https://github.com/paradigmxyz/reth/issues/10179
- [ ] https://github.com/paradigmxyz/reth/issues/10187
- [ ] https://github.com/paradigmxyz/reth/issues/10186
- [ ] https://github.com/paradigmxyz/reth/issues/10220
- [ ] https://github.com/paradigmxyz/reth/issues/10221
- [ ] https://github.com/paradigmxyz/reth/issues/10219
- [ ] https://github.com/paradigmxyz/reth/issues/10489
- [ ] https://github.com/paradigmxyz/reth/issues/8751
- [ ] https://github.com/paradigmxyz/reth/issues/11251
```

**Comment by emhane** [comment]
will solve these issues https://github.com/paradigmxyz/reth/issues/8303, especially https://github.com/paradigmxyz/reth/issues/8746 and https://github.com/paradigmxyz/reth/issues/8745

**Comment by emhane** [comment]
https://github.com/paradigmxyz/reth/issues/8745 and https://github.com/paradigmxyz/reth/issues/8746 should solve https://github.com/paradigmxyz/reth/issues/7322
