### ISSUE TITLE
Access RPC types via alloy `Network` trait in `EthApi`

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8780]
### Describe the feature

Replace alloy rpc types `AnyTransactionReceipt`, `RichBlock` and `Transaction` in `EthApi` trait, with `Network` trait.

https://github.com/alloy-rs/alloy/blob/251e11ebde5fae1b94652c5b0109d5d966726f55/crates/network/src/lib.rs#L48-L101

This will also have to happen for `EngineEthApi`, due to trait bound 

https://github.com/paradigmxyz/reth/blob/b8cd7be6c92a71aea5341cdeba685f124c6de540/crates/rpc/rpc/src/engine.rs#L35

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/9523
- [ ] https://github.com/paradigmxyz/reth/pull/10417
- [ ] https://github.com/paradigmxyz/reth/pull/9774
- [ ] https://github.com/paradigmxyz/reth/issues/10451
- [ ] https://github.com/paradigmxyz/reth/issues/10452
```
