### ISSUE TITLE
EIP-7251: EL Triggered Consolidations

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8786]
### Describe the feature

This is now in the devnet-1 spec, and adds a new system call that the EL has to implement, so it should be implemented in reth.

This involves a few things:
 - [x] Addition of a new consolidations EIP-7685 request type: https://github.com/alloy-rs/alloy/issues/884
 - [x] Addition of new consolidations constants (added in https://github.com/alloy-rs/alloy/pull/956)
 - [ ] Consolidation request fee calculations
 - [ ] Consolidation system contract
   - [ ] The contract call itself
   - [ ] Request list validation
     - From the EIP:
        > Check that consolidation requests in the [EIP-7685](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7685.md) requests list matches the list returned from dequeue_consolidation_requests() function of the smart contract respecting the order of the returned requests. If this condition does not hold, the block MUST be deemed invalid.
 - [ ] Updates to engine API: https://github.com/ethereum/execution-apis/pull/554

### Additional context

EIP link: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7251.md
