### ISSUE TITLE
Tracking: Prague devnet-1

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8788]
```[tasklist]
### Devnet-1
- [ ] https://github.com/alloy-rs/alloy/issues/884
- [ ] https://github.com/alloy-rs/alloy/issues/886
- [ ] https://github.com/paradigmxyz/reth/issues/8786
- [ ] https://github.com/paradigmxyz/reth/issues/8787
- [ ] https://github.com/paradigmxyz/reth/pull/9214
- [ ] https://github.com/paradigmxyz/reth/issues/8379
- [ ] https://github.com/paradigmxyz/reth/issues/9428
```

Devnet 1 specs: https://notes.ethereum.org/@ethpandaops/pectra-devnet-1
