### ISSUE TITLE
Remove Optimism feature from chainspec

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#8904]
### Describe the feature

this is closely related to #7679 

we should find a way to get rid of optimism specific stuff in chainspec, either by switching to name based hardforks, or a trait abstraction for chainspec.

in the short term, I think using named variants as described in #7679 would be easier and would allow adding additional hardforks and check functions via extension traits

or we go all the way and add trait for chainspec.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/issues/10468
- [ ] https://github.com/paradigmxyz/reth/pull/10485
- [ ] https://github.com/paradigmxyz/reth/issues/10518
- [ ] https://github.com/paradigmxyz/reth/issues/10513
- [ ] https://github.com/paradigmxyz/reth/pull/10944#event-14288349483
- [ ] https://github.com/paradigmxyz/reth/pull/9065
- [ ] https://github.com/paradigmxyz/reth/issues/11238
- [ ] https://github.com/paradigmxyz/reth/issues/11396
- [ ] https://github.com/paradigmxyz/reth/issues/11397
- [ ] https://github.com/paradigmxyz/reth/issues/11561
```
