### ISSUE TITLE
Tracking: Live sync execution optimization

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8964]
There are a few things we can do to improve execution performance at the tip:

```[tasklist]
### Tasks 
- [ ] Precompile cache - see https://github.com/paradigmxyz/reth/blob/main/examples/stateful-precompile/src/main.rs for the general idea
- [ ] Fetching proofs while executing
- [ ] Parallel execution for caching trie and state
```
