### ISSUE TITLE
Basic `reth stage` cli command flow testing

### ISSUE THREAD

**Issue by Rjected** [paradigmxyz/reth#8975]
Right now we do not have any integration testing for most of the commands that we include, such as `stage unwind`, `stage run`, etc. We can check that these commands work at the very least, by running them in CI.

We would want to test at least the following commands:
```[tasklist]
### Tasks
- [ ] reth stage run (for each stage)
- [ ] reth stage unwind num-blocks
- [ ] reth stage unwind to-block
```

See https://github.com/paradigmxyz/reth/pull/8974 for the first kind of example of this

**Comment by greged93** [comment]
hey @Rjected, I'm down to work on this

**Comment by Rjected** [comment]
hey @greged93 would you still like to work on this?

**Comment by greged93** [comment]
Hey @Rjected, yes, I would be able to start on Monday if that works, if the work is urgent then no worries

**Comment by Rjected** [comment]
> Hey @Rjected, yes, I would be able to start on Monday if that works, if the work is urgent then no worries

that sounds good! just assigned
