### ISSUE TITLE
Remove optimism feature from rpc crates

### ISSUE THREAD

**Issue by emhane** [paradigmxyz/reth#8988]
### Describe the feature

Tracking rpc crates rebuild to accommodate for custom RPC server. In process of making node generic over `EthApiServer` impl, code is simplified w.r.t. node builder pattern.

Rn the code for optimism is embedded into the L1 code using compiler feature gating. These changes will make it possible to detangle the optimism code from the L1 code, so optimism can be used a separate library.

```[tasklist]
### Tasks
- [ ] https://github.com/paradigmxyz/reth/pull/8437
- [ ] https://github.com/paradigmxyz/reth/pull/8411
- [ ] https://github.com/paradigmxyz/reth/pull/8538
- [ ] https://github.com/paradigmxyz/reth/pull/8640
- [ ] https://github.com/paradigmxyz/reth/pull/8639
- [ ] https://github.com/paradigmxyz/reth/pull/8659
- [ ] https://github.com/paradigmxyz/reth/pull/8683
- [ ] https://github.com/paradigmxyz/reth/pull/8723
- [ ] https://github.com/paradigmxyz/reth/pull/8759
- [ ] https://github.com/paradigmxyz/reth/issues/8776
- [ ] https://github.com/paradigmxyz/reth/issues/8780
- [ ] https://github.com/paradigmxyz/reth/issues/8781
- [ ] https://github.com/paradigmxyz/reth/issues/8985
- [ ] https://github.com/paradigmxyz/reth/issues/8986
- [ ] https://github.com/paradigmxyz/reth/issues/9408
- [ ] https://github.com/paradigmxyz/reth/pull/9502
- [ ] https://github.com/paradigmxyz/reth/issues/9323
- [ ] https://github.com/paradigmxyz/reth/issues/9296
- [ ] https://github.com/paradigmxyz/reth/issues/9325
- [ ] https://github.com/paradigmxyz/reth/pull/9774
```
