### ISSUE TITLE
Reusable command implementations

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9038]
### Describe the feature

currently all commands are in the reth binary crate and are shared with the optimism binary.

we expect that more networks would like to use existing commands. to make this easier we need a way to reuse them, independent of the reth `Cli` type.

this likely needs some form of separation of type-def and impl.

```[tasklist]
- [ ] incrementally move commands to a commands crate
- [ ] https://github.com/paradigmxyz/reth/issues/9084
- [ ] https://github.com/paradigmxyz/reth/issues/9219
```

**Comment by mattsse** [comment]
completed
