### ISSUE TITLE
Tracking Optimism RPC support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9294]
### Describe the feature

Add standalone OP RPC support

```[tasklist]
- [ ] https://github.com/paradigmxyz/reth/issues/9296
- [ ] https://github.com/paradigmxyz/reth/issues/9323
- [ ] https://github.com/paradigmxyz/reth/issues/9325
```

**Comment by emhane** [comment]
duplicate of https://github.com/paradigmxyz/reth/issues/8988
