### ISSUE TITLE
Fix various compilation errors for no-std in crates

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/reth#9478]
### Describe the feature

crates that are offending cargo c --no-default-features

* ethereum-forks
* primitives
* primitives-traits
* ...

## TODO
* fix by doing various fix like

```
#[cfg(not(feature = "std"))]
use alloc::vec::Vec;
```
extern crate alloc 

etc

**Comment by leruaa** [comment]
I can work on this.

**Comment by martinezjorge** [comment]
May I?

**Comment by mattsse** [comment]
assigned, usually the todos are using `core` instead of `std` and `alloc` over `std`

**Comment by martinezjorge** [comment]
I went through all the crates running the command below:

> cargo c --no-default-features -p <crate_name>

and the following crates had compilation error:

- [x] reth-consensus 
- [x] reth-evm-ethereum
- [x] reth-ethereum-forks
- [x] reth-evm
- [x] reth-execution-errors
- [ ] reth-network-api
- [x] reth-primitives
- [x] reth-primitives-traits
- [x] reth-revm
- [ ] reth-rpc-types
- [x] reth-storage-errors

Just need two more but the last two are the ones I'm having more trouble with

**Comment by martinezjorge** [comment]
Yeah that one is erroring for me, I must have missed it or something was updated that caused it to offend. In any case, I've added `reth-db` to the list. 

As more code is added to main there will likely be others until #9479 is closed. Let me know if you notice any others.

I'm currently working on `reth-primitives`, let me know what you're working on or when you start a new one so we don't duplicate efforts.

**Comment by martinezjorge** [comment]
@mattsse 

Just wanted to report that as of now I've ceased work on this issue. 

We are able to get some of the packages supporting no_std and at least compiled a list of the crates that are offending the `no_std` check. The ones that are left are a little beyond my knowledge and, I believe, require extra care in how they are handled.

As @nkysg noted, jsonrpsee does not support `no_std` and the other packages like `reth-primitives`, `reth-execution-errors`, `reth-consensus`, `reth-revm`, and `reth-storage-errors` are all entangled and might require to be handled at the same time. Regardless, the changes to fix them are so large that I don't think they will be in a small manageable PR and thus without guidance I don't think I can continue working on this issue.

**Comment by citizen-stig** [comment]
Hello!

I just want to point out, that it looks like that [`thiserror-no-std`](https://docs.rs/thiserror-no-std/2.0.2/thiserror_no_std/) might be not the best candidate for usage. 

Documentation page does not point to the actual repo, which is https://github.com/Stupremee/thiserror and it hasn't been updated in 2 years, which is a little bit concerning.

But most importantly, it does not work:


```
cargo check --no-default-features` on reth-primitives

info: running `cargo check --no-default-features` on reth-primitives (7/234)
    Checking reth-primitives v1.0.3 (/Users/nikolai/workspace/sovereign/reth/crates/primitives)
error[E0433]: failed to resolve: use of undeclared crate or module `std`
 --> crates/primitives/src/transaction/error.rs:6:1
  |
6 | pub enum InvalidTransactionError {
  | ^^^ use of undeclared crate or module `std`
  |
help: consider importing this module
  |
1 + use core::error;
```

https://github.com/Stupremee/thiserror/blob/2fd08ccb500231c600083f88c4d2b68ad7024255/src/aserror.rs#L1


Considering that original author of thiserror is not keen on support of the no_std: https://github.com/dtolnay/thiserror/pull/64

It might be a good time to reconsider how this is handled in reth.

**Comment by martinezjorge** [comment]
@mattsse 

All of the crates pass `cargo c -p <package_name> --no-default-features so I'm thinking we can close this issue

**Comment by martinezjorge** [comment]
@mattse is there something I'm missing here? I'd be happy to keep working on it, just let me know

**Comment by mattsse** [comment]
marking this as complete tysm @martinezjorge
